// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package AutoscalarAutoscalingPolicyCpuUtilization

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type AutoscalarAutoscalingPolicyCpuUtilization struct {
	Target float64 `pulumi:"target"`
}

type AutoscalarAutoscalingPolicyCpuUtilizationInput interface {
	pulumi.Input

	ToAutoscalarAutoscalingPolicyCpuUtilizationOutput() AutoscalarAutoscalingPolicyCpuUtilizationOutput
	ToAutoscalarAutoscalingPolicyCpuUtilizationOutputWithContext(context.Context) AutoscalarAutoscalingPolicyCpuUtilizationOutput
}

type AutoscalarAutoscalingPolicyCpuUtilizationArgs struct {
	Target pulumi.Float64Input `pulumi:"target"`
}

func (AutoscalarAutoscalingPolicyCpuUtilizationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AutoscalarAutoscalingPolicyCpuUtilization)(nil)).Elem()
}

func (i AutoscalarAutoscalingPolicyCpuUtilizationArgs) ToAutoscalarAutoscalingPolicyCpuUtilizationOutput() AutoscalarAutoscalingPolicyCpuUtilizationOutput {
	return i.ToAutoscalarAutoscalingPolicyCpuUtilizationOutputWithContext(context.Background())
}

func (i AutoscalarAutoscalingPolicyCpuUtilizationArgs) ToAutoscalarAutoscalingPolicyCpuUtilizationOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyCpuUtilizationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AutoscalarAutoscalingPolicyCpuUtilizationOutput)
}

func (i AutoscalarAutoscalingPolicyCpuUtilizationArgs) ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutput() AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput {
	return i.ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(context.Background())
}

func (i AutoscalarAutoscalingPolicyCpuUtilizationArgs) ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AutoscalarAutoscalingPolicyCpuUtilizationOutput).ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(ctx)
}

type AutoscalarAutoscalingPolicyCpuUtilizationPtrInput interface {
	pulumi.Input

	ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutput() AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput
	ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(context.Context) AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput
}

type autoscalarAutoscalingPolicyCpuUtilizationPtrType AutoscalarAutoscalingPolicyCpuUtilizationArgs

func AutoscalarAutoscalingPolicyCpuUtilizationPtr(v *AutoscalarAutoscalingPolicyCpuUtilizationArgs) AutoscalarAutoscalingPolicyCpuUtilizationPtrInput {	return (*autoscalarAutoscalingPolicyCpuUtilizationPtrType)(v)
}

func (*autoscalarAutoscalingPolicyCpuUtilizationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AutoscalarAutoscalingPolicyCpuUtilization)(nil)).Elem()
}

func (i *autoscalarAutoscalingPolicyCpuUtilizationPtrType) ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutput() AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput {
	return i.ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(context.Background())
}

func (i *autoscalarAutoscalingPolicyCpuUtilizationPtrType) ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput)
}

type AutoscalarAutoscalingPolicyCpuUtilizationOutput struct { *pulumi.OutputState }

func (AutoscalarAutoscalingPolicyCpuUtilizationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AutoscalarAutoscalingPolicyCpuUtilization)(nil)).Elem()
}

func (o AutoscalarAutoscalingPolicyCpuUtilizationOutput) ToAutoscalarAutoscalingPolicyCpuUtilizationOutput() AutoscalarAutoscalingPolicyCpuUtilizationOutput {
	return o
}

func (o AutoscalarAutoscalingPolicyCpuUtilizationOutput) ToAutoscalarAutoscalingPolicyCpuUtilizationOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyCpuUtilizationOutput {
	return o
}

func (o AutoscalarAutoscalingPolicyCpuUtilizationOutput) ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutput() AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput {
	return o.ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(context.Background())
}

func (o AutoscalarAutoscalingPolicyCpuUtilizationOutput) ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput {
	return o.ApplyT(func(v AutoscalarAutoscalingPolicyCpuUtilization) *AutoscalarAutoscalingPolicyCpuUtilization {
		return &v
	}).(AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput)
}
func (o AutoscalarAutoscalingPolicyCpuUtilizationOutput) Target() pulumi.Float64Output {
	return o.ApplyT(func (v AutoscalarAutoscalingPolicyCpuUtilization) float64 { return v.Target }).(pulumi.Float64Output)
}

type AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput struct { *pulumi.OutputState}

func (AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AutoscalarAutoscalingPolicyCpuUtilization)(nil)).Elem()
}

func (o AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput) ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutput() AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput {
	return o
}

func (o AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput) ToAutoscalarAutoscalingPolicyCpuUtilizationPtrOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput {
	return o
}

func (o AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput) Elem() AutoscalarAutoscalingPolicyCpuUtilizationOutput {
	return o.ApplyT(func (v *AutoscalarAutoscalingPolicyCpuUtilization) AutoscalarAutoscalingPolicyCpuUtilization { return *v }).(AutoscalarAutoscalingPolicyCpuUtilizationOutput)
}

func (o AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput) Target() pulumi.Float64Output {
	return o.ApplyT(func (v AutoscalarAutoscalingPolicyCpuUtilization) float64 { return v.Target }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterOutputType(AutoscalarAutoscalingPolicyCpuUtilizationOutput{})
	pulumi.RegisterOutputType(AutoscalarAutoscalingPolicyCpuUtilizationPtrOutput{})
}
