[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "master"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-google"
  source = "github.com/pulumi/terraform-provider-google"
  # branch = "pulumi-master"
  revision = "8711ef707678f23abb737cb5930faa32028e1956"
