// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package JobHiveConfig

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type JobHiveConfig struct {
	ContinueOnFailure *bool `pulumi:"continueOnFailure"`
	JarFileUris []string `pulumi:"jarFileUris"`
	Properties map[string]string `pulumi:"properties"`
	QueryFileUri *string `pulumi:"queryFileUri"`
	QueryLists []string `pulumi:"queryLists"`
	ScriptVariables map[string]string `pulumi:"scriptVariables"`
}

type JobHiveConfigInput interface {
	pulumi.Input

	ToJobHiveConfigOutput() JobHiveConfigOutput
	ToJobHiveConfigOutputWithContext(context.Context) JobHiveConfigOutput
}

type JobHiveConfigArgs struct {
	ContinueOnFailure pulumi.BoolPtrInput `pulumi:"continueOnFailure"`
	JarFileUris pulumi.StringArrayInput `pulumi:"jarFileUris"`
	Properties pulumi.StringMapInput `pulumi:"properties"`
	QueryFileUri pulumi.StringPtrInput `pulumi:"queryFileUri"`
	QueryLists pulumi.StringArrayInput `pulumi:"queryLists"`
	ScriptVariables pulumi.StringMapInput `pulumi:"scriptVariables"`
}

func (JobHiveConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*JobHiveConfig)(nil)).Elem()
}

func (i JobHiveConfigArgs) ToJobHiveConfigOutput() JobHiveConfigOutput {
	return i.ToJobHiveConfigOutputWithContext(context.Background())
}

func (i JobHiveConfigArgs) ToJobHiveConfigOutputWithContext(ctx context.Context) JobHiveConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHiveConfigOutput)
}

func (i JobHiveConfigArgs) ToJobHiveConfigPtrOutput() JobHiveConfigPtrOutput {
	return i.ToJobHiveConfigPtrOutputWithContext(context.Background())
}

func (i JobHiveConfigArgs) ToJobHiveConfigPtrOutputWithContext(ctx context.Context) JobHiveConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHiveConfigOutput).ToJobHiveConfigPtrOutputWithContext(ctx)
}

type JobHiveConfigPtrInput interface {
	pulumi.Input

	ToJobHiveConfigPtrOutput() JobHiveConfigPtrOutput
	ToJobHiveConfigPtrOutputWithContext(context.Context) JobHiveConfigPtrOutput
}

type jobHiveConfigPtrType JobHiveConfigArgs

func JobHiveConfigPtr(v *JobHiveConfigArgs) JobHiveConfigPtrInput {	return (*jobHiveConfigPtrType)(v)
}

func (*jobHiveConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**JobHiveConfig)(nil)).Elem()
}

func (i *jobHiveConfigPtrType) ToJobHiveConfigPtrOutput() JobHiveConfigPtrOutput {
	return i.ToJobHiveConfigPtrOutputWithContext(context.Background())
}

func (i *jobHiveConfigPtrType) ToJobHiveConfigPtrOutputWithContext(ctx context.Context) JobHiveConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHiveConfigPtrOutput)
}

type JobHiveConfigOutput struct { *pulumi.OutputState }

func (JobHiveConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*JobHiveConfig)(nil)).Elem()
}

func (o JobHiveConfigOutput) ToJobHiveConfigOutput() JobHiveConfigOutput {
	return o
}

func (o JobHiveConfigOutput) ToJobHiveConfigOutputWithContext(ctx context.Context) JobHiveConfigOutput {
	return o
}

func (o JobHiveConfigOutput) ToJobHiveConfigPtrOutput() JobHiveConfigPtrOutput {
	return o.ToJobHiveConfigPtrOutputWithContext(context.Background())
}

func (o JobHiveConfigOutput) ToJobHiveConfigPtrOutputWithContext(ctx context.Context) JobHiveConfigPtrOutput {
	return o.ApplyT(func(v JobHiveConfig) *JobHiveConfig {
		return &v
	}).(JobHiveConfigPtrOutput)
}
func (o JobHiveConfigOutput) ContinueOnFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v JobHiveConfig) *bool { return v.ContinueOnFailure }).(pulumi.BoolPtrOutput)
}

func (o JobHiveConfigOutput) JarFileUris() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHiveConfig) []string { return v.JarFileUris }).(pulumi.StringArrayOutput)
}

func (o JobHiveConfigOutput) Properties() pulumi.StringMapOutput {
	return o.ApplyT(func (v JobHiveConfig) map[string]string { return v.Properties }).(pulumi.StringMapOutput)
}

func (o JobHiveConfigOutput) QueryFileUri() pulumi.StringPtrOutput {
	return o.ApplyT(func (v JobHiveConfig) *string { return v.QueryFileUri }).(pulumi.StringPtrOutput)
}

func (o JobHiveConfigOutput) QueryLists() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHiveConfig) []string { return v.QueryLists }).(pulumi.StringArrayOutput)
}

func (o JobHiveConfigOutput) ScriptVariables() pulumi.StringMapOutput {
	return o.ApplyT(func (v JobHiveConfig) map[string]string { return v.ScriptVariables }).(pulumi.StringMapOutput)
}

type JobHiveConfigPtrOutput struct { *pulumi.OutputState}

func (JobHiveConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**JobHiveConfig)(nil)).Elem()
}

func (o JobHiveConfigPtrOutput) ToJobHiveConfigPtrOutput() JobHiveConfigPtrOutput {
	return o
}

func (o JobHiveConfigPtrOutput) ToJobHiveConfigPtrOutputWithContext(ctx context.Context) JobHiveConfigPtrOutput {
	return o
}

func (o JobHiveConfigPtrOutput) Elem() JobHiveConfigOutput {
	return o.ApplyT(func (v *JobHiveConfig) JobHiveConfig { return *v }).(JobHiveConfigOutput)
}

func (o JobHiveConfigPtrOutput) ContinueOnFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v JobHiveConfig) *bool { return v.ContinueOnFailure }).(pulumi.BoolPtrOutput)
}

func (o JobHiveConfigPtrOutput) JarFileUris() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHiveConfig) []string { return v.JarFileUris }).(pulumi.StringArrayOutput)
}

func (o JobHiveConfigPtrOutput) Properties() pulumi.StringMapOutput {
	return o.ApplyT(func (v JobHiveConfig) map[string]string { return v.Properties }).(pulumi.StringMapOutput)
}

func (o JobHiveConfigPtrOutput) QueryFileUri() pulumi.StringPtrOutput {
	return o.ApplyT(func (v JobHiveConfig) *string { return v.QueryFileUri }).(pulumi.StringPtrOutput)
}

func (o JobHiveConfigPtrOutput) QueryLists() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHiveConfig) []string { return v.QueryLists }).(pulumi.StringArrayOutput)
}

func (o JobHiveConfigPtrOutput) ScriptVariables() pulumi.StringMapOutput {
	return o.ApplyT(func (v JobHiveConfig) map[string]string { return v.ScriptVariables }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(JobHiveConfigOutput{})
	pulumi.RegisterOutputType(JobHiveConfigPtrOutput{})
}
