// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package ClusterClusterConfigEncryptionConfig

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type ClusterClusterConfigEncryptionConfig struct {
	KmsKeyName string `pulumi:"kmsKeyName"`
}

type ClusterClusterConfigEncryptionConfigInput interface {
	pulumi.Input

	ToClusterClusterConfigEncryptionConfigOutput() ClusterClusterConfigEncryptionConfigOutput
	ToClusterClusterConfigEncryptionConfigOutputWithContext(context.Context) ClusterClusterConfigEncryptionConfigOutput
}

type ClusterClusterConfigEncryptionConfigArgs struct {
	KmsKeyName pulumi.StringInput `pulumi:"kmsKeyName"`
}

func (ClusterClusterConfigEncryptionConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterClusterConfigEncryptionConfig)(nil)).Elem()
}

func (i ClusterClusterConfigEncryptionConfigArgs) ToClusterClusterConfigEncryptionConfigOutput() ClusterClusterConfigEncryptionConfigOutput {
	return i.ToClusterClusterConfigEncryptionConfigOutputWithContext(context.Background())
}

func (i ClusterClusterConfigEncryptionConfigArgs) ToClusterClusterConfigEncryptionConfigOutputWithContext(ctx context.Context) ClusterClusterConfigEncryptionConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterClusterConfigEncryptionConfigOutput)
}

func (i ClusterClusterConfigEncryptionConfigArgs) ToClusterClusterConfigEncryptionConfigPtrOutput() ClusterClusterConfigEncryptionConfigPtrOutput {
	return i.ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(context.Background())
}

func (i ClusterClusterConfigEncryptionConfigArgs) ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(ctx context.Context) ClusterClusterConfigEncryptionConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterClusterConfigEncryptionConfigOutput).ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(ctx)
}

type ClusterClusterConfigEncryptionConfigPtrInput interface {
	pulumi.Input

	ToClusterClusterConfigEncryptionConfigPtrOutput() ClusterClusterConfigEncryptionConfigPtrOutput
	ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(context.Context) ClusterClusterConfigEncryptionConfigPtrOutput
}

type clusterClusterConfigEncryptionConfigPtrType ClusterClusterConfigEncryptionConfigArgs

func ClusterClusterConfigEncryptionConfigPtr(v *ClusterClusterConfigEncryptionConfigArgs) ClusterClusterConfigEncryptionConfigPtrInput {	return (*clusterClusterConfigEncryptionConfigPtrType)(v)
}

func (*clusterClusterConfigEncryptionConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterClusterConfigEncryptionConfig)(nil)).Elem()
}

func (i *clusterClusterConfigEncryptionConfigPtrType) ToClusterClusterConfigEncryptionConfigPtrOutput() ClusterClusterConfigEncryptionConfigPtrOutput {
	return i.ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(context.Background())
}

func (i *clusterClusterConfigEncryptionConfigPtrType) ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(ctx context.Context) ClusterClusterConfigEncryptionConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterClusterConfigEncryptionConfigPtrOutput)
}

type ClusterClusterConfigEncryptionConfigOutput struct { *pulumi.OutputState }

func (ClusterClusterConfigEncryptionConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterClusterConfigEncryptionConfig)(nil)).Elem()
}

func (o ClusterClusterConfigEncryptionConfigOutput) ToClusterClusterConfigEncryptionConfigOutput() ClusterClusterConfigEncryptionConfigOutput {
	return o
}

func (o ClusterClusterConfigEncryptionConfigOutput) ToClusterClusterConfigEncryptionConfigOutputWithContext(ctx context.Context) ClusterClusterConfigEncryptionConfigOutput {
	return o
}

func (o ClusterClusterConfigEncryptionConfigOutput) ToClusterClusterConfigEncryptionConfigPtrOutput() ClusterClusterConfigEncryptionConfigPtrOutput {
	return o.ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(context.Background())
}

func (o ClusterClusterConfigEncryptionConfigOutput) ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(ctx context.Context) ClusterClusterConfigEncryptionConfigPtrOutput {
	return o.ApplyT(func(v ClusterClusterConfigEncryptionConfig) *ClusterClusterConfigEncryptionConfig {
		return &v
	}).(ClusterClusterConfigEncryptionConfigPtrOutput)
}
func (o ClusterClusterConfigEncryptionConfigOutput) KmsKeyName() pulumi.StringOutput {
	return o.ApplyT(func (v ClusterClusterConfigEncryptionConfig) string { return v.KmsKeyName }).(pulumi.StringOutput)
}

type ClusterClusterConfigEncryptionConfigPtrOutput struct { *pulumi.OutputState}

func (ClusterClusterConfigEncryptionConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterClusterConfigEncryptionConfig)(nil)).Elem()
}

func (o ClusterClusterConfigEncryptionConfigPtrOutput) ToClusterClusterConfigEncryptionConfigPtrOutput() ClusterClusterConfigEncryptionConfigPtrOutput {
	return o
}

func (o ClusterClusterConfigEncryptionConfigPtrOutput) ToClusterClusterConfigEncryptionConfigPtrOutputWithContext(ctx context.Context) ClusterClusterConfigEncryptionConfigPtrOutput {
	return o
}

func (o ClusterClusterConfigEncryptionConfigPtrOutput) Elem() ClusterClusterConfigEncryptionConfigOutput {
	return o.ApplyT(func (v *ClusterClusterConfigEncryptionConfig) ClusterClusterConfigEncryptionConfig { return *v }).(ClusterClusterConfigEncryptionConfigOutput)
}

func (o ClusterClusterConfigEncryptionConfigPtrOutput) KmsKeyName() pulumi.StringOutput {
	return o.ApplyT(func (v ClusterClusterConfigEncryptionConfig) string { return v.KmsKeyName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(ClusterClusterConfigEncryptionConfigOutput{})
	pulumi.RegisterOutputType(ClusterClusterConfigEncryptionConfigPtrOutput{})
}
