// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package MetricMetricDescriptorLabel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type MetricMetricDescriptorLabel struct {
	Description *string `pulumi:"description"`
	Key string `pulumi:"key"`
	ValueType *string `pulumi:"valueType"`
}

type MetricMetricDescriptorLabelInput interface {
	pulumi.Input

	ToMetricMetricDescriptorLabelOutput() MetricMetricDescriptorLabelOutput
	ToMetricMetricDescriptorLabelOutputWithContext(context.Context) MetricMetricDescriptorLabelOutput
}

type MetricMetricDescriptorLabelArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Key pulumi.StringInput `pulumi:"key"`
	ValueType pulumi.StringPtrInput `pulumi:"valueType"`
}

func (MetricMetricDescriptorLabelArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*MetricMetricDescriptorLabel)(nil)).Elem()
}

func (i MetricMetricDescriptorLabelArgs) ToMetricMetricDescriptorLabelOutput() MetricMetricDescriptorLabelOutput {
	return i.ToMetricMetricDescriptorLabelOutputWithContext(context.Background())
}

func (i MetricMetricDescriptorLabelArgs) ToMetricMetricDescriptorLabelOutputWithContext(ctx context.Context) MetricMetricDescriptorLabelOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MetricMetricDescriptorLabelOutput)
}

type MetricMetricDescriptorLabelArrayInput interface {
	pulumi.Input

	ToMetricMetricDescriptorLabelArrayOutput() MetricMetricDescriptorLabelArrayOutput
	ToMetricMetricDescriptorLabelArrayOutputWithContext(context.Context) MetricMetricDescriptorLabelArrayOutput
}

type MetricMetricDescriptorLabelArray []MetricMetricDescriptorLabelInput

func (MetricMetricDescriptorLabelArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]MetricMetricDescriptorLabel)(nil)).Elem()
}

func (i MetricMetricDescriptorLabelArray) ToMetricMetricDescriptorLabelArrayOutput() MetricMetricDescriptorLabelArrayOutput {
	return i.ToMetricMetricDescriptorLabelArrayOutputWithContext(context.Background())
}

func (i MetricMetricDescriptorLabelArray) ToMetricMetricDescriptorLabelArrayOutputWithContext(ctx context.Context) MetricMetricDescriptorLabelArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MetricMetricDescriptorLabelArrayOutput)
}

type MetricMetricDescriptorLabelOutput struct { *pulumi.OutputState }

func (MetricMetricDescriptorLabelOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*MetricMetricDescriptorLabel)(nil)).Elem()
}

func (o MetricMetricDescriptorLabelOutput) ToMetricMetricDescriptorLabelOutput() MetricMetricDescriptorLabelOutput {
	return o
}

func (o MetricMetricDescriptorLabelOutput) ToMetricMetricDescriptorLabelOutputWithContext(ctx context.Context) MetricMetricDescriptorLabelOutput {
	return o
}

func (o MetricMetricDescriptorLabelOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func (v MetricMetricDescriptorLabel) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o MetricMetricDescriptorLabelOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func (v MetricMetricDescriptorLabel) string { return v.Key }).(pulumi.StringOutput)
}

func (o MetricMetricDescriptorLabelOutput) ValueType() pulumi.StringPtrOutput {
	return o.ApplyT(func (v MetricMetricDescriptorLabel) *string { return v.ValueType }).(pulumi.StringPtrOutput)
}

type MetricMetricDescriptorLabelArrayOutput struct { *pulumi.OutputState}

func (MetricMetricDescriptorLabelArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]MetricMetricDescriptorLabel)(nil)).Elem()
}

func (o MetricMetricDescriptorLabelArrayOutput) ToMetricMetricDescriptorLabelArrayOutput() MetricMetricDescriptorLabelArrayOutput {
	return o
}

func (o MetricMetricDescriptorLabelArrayOutput) ToMetricMetricDescriptorLabelArrayOutputWithContext(ctx context.Context) MetricMetricDescriptorLabelArrayOutput {
	return o
}

func (o MetricMetricDescriptorLabelArrayOutput) Index(i pulumi.IntInput) MetricMetricDescriptorLabelOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) MetricMetricDescriptorLabel {
		return vs[0].([]MetricMetricDescriptorLabel)[vs[1].(int)]
	}).(MetricMetricDescriptorLabelOutput)
}

func init() {
	pulumi.RegisterOutputType(MetricMetricDescriptorLabelOutput{})
	pulumi.RegisterOutputType(MetricMetricDescriptorLabelArrayOutput{})
}
