// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package TopicMessageStoragePolicy

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type TopicMessageStoragePolicy struct {
	AllowedPersistenceRegions []string `pulumi:"allowedPersistenceRegions"`
}

type TopicMessageStoragePolicyInput interface {
	pulumi.Input

	ToTopicMessageStoragePolicyOutput() TopicMessageStoragePolicyOutput
	ToTopicMessageStoragePolicyOutputWithContext(context.Context) TopicMessageStoragePolicyOutput
}

type TopicMessageStoragePolicyArgs struct {
	AllowedPersistenceRegions pulumi.StringArrayInput `pulumi:"allowedPersistenceRegions"`
}

func (TopicMessageStoragePolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TopicMessageStoragePolicy)(nil)).Elem()
}

func (i TopicMessageStoragePolicyArgs) ToTopicMessageStoragePolicyOutput() TopicMessageStoragePolicyOutput {
	return i.ToTopicMessageStoragePolicyOutputWithContext(context.Background())
}

func (i TopicMessageStoragePolicyArgs) ToTopicMessageStoragePolicyOutputWithContext(ctx context.Context) TopicMessageStoragePolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TopicMessageStoragePolicyOutput)
}

func (i TopicMessageStoragePolicyArgs) ToTopicMessageStoragePolicyPtrOutput() TopicMessageStoragePolicyPtrOutput {
	return i.ToTopicMessageStoragePolicyPtrOutputWithContext(context.Background())
}

func (i TopicMessageStoragePolicyArgs) ToTopicMessageStoragePolicyPtrOutputWithContext(ctx context.Context) TopicMessageStoragePolicyPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TopicMessageStoragePolicyOutput).ToTopicMessageStoragePolicyPtrOutputWithContext(ctx)
}

type TopicMessageStoragePolicyPtrInput interface {
	pulumi.Input

	ToTopicMessageStoragePolicyPtrOutput() TopicMessageStoragePolicyPtrOutput
	ToTopicMessageStoragePolicyPtrOutputWithContext(context.Context) TopicMessageStoragePolicyPtrOutput
}

type topicMessageStoragePolicyPtrType TopicMessageStoragePolicyArgs

func TopicMessageStoragePolicyPtr(v *TopicMessageStoragePolicyArgs) TopicMessageStoragePolicyPtrInput {	return (*topicMessageStoragePolicyPtrType)(v)
}

func (*topicMessageStoragePolicyPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**TopicMessageStoragePolicy)(nil)).Elem()
}

func (i *topicMessageStoragePolicyPtrType) ToTopicMessageStoragePolicyPtrOutput() TopicMessageStoragePolicyPtrOutput {
	return i.ToTopicMessageStoragePolicyPtrOutputWithContext(context.Background())
}

func (i *topicMessageStoragePolicyPtrType) ToTopicMessageStoragePolicyPtrOutputWithContext(ctx context.Context) TopicMessageStoragePolicyPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TopicMessageStoragePolicyPtrOutput)
}

type TopicMessageStoragePolicyOutput struct { *pulumi.OutputState }

func (TopicMessageStoragePolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TopicMessageStoragePolicy)(nil)).Elem()
}

func (o TopicMessageStoragePolicyOutput) ToTopicMessageStoragePolicyOutput() TopicMessageStoragePolicyOutput {
	return o
}

func (o TopicMessageStoragePolicyOutput) ToTopicMessageStoragePolicyOutputWithContext(ctx context.Context) TopicMessageStoragePolicyOutput {
	return o
}

func (o TopicMessageStoragePolicyOutput) ToTopicMessageStoragePolicyPtrOutput() TopicMessageStoragePolicyPtrOutput {
	return o.ToTopicMessageStoragePolicyPtrOutputWithContext(context.Background())
}

func (o TopicMessageStoragePolicyOutput) ToTopicMessageStoragePolicyPtrOutputWithContext(ctx context.Context) TopicMessageStoragePolicyPtrOutput {
	return o.ApplyT(func(v TopicMessageStoragePolicy) *TopicMessageStoragePolicy {
		return &v
	}).(TopicMessageStoragePolicyPtrOutput)
}
func (o TopicMessageStoragePolicyOutput) AllowedPersistenceRegions() pulumi.StringArrayOutput {
	return o.ApplyT(func (v TopicMessageStoragePolicy) []string { return v.AllowedPersistenceRegions }).(pulumi.StringArrayOutput)
}

type TopicMessageStoragePolicyPtrOutput struct { *pulumi.OutputState}

func (TopicMessageStoragePolicyPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TopicMessageStoragePolicy)(nil)).Elem()
}

func (o TopicMessageStoragePolicyPtrOutput) ToTopicMessageStoragePolicyPtrOutput() TopicMessageStoragePolicyPtrOutput {
	return o
}

func (o TopicMessageStoragePolicyPtrOutput) ToTopicMessageStoragePolicyPtrOutputWithContext(ctx context.Context) TopicMessageStoragePolicyPtrOutput {
	return o
}

func (o TopicMessageStoragePolicyPtrOutput) Elem() TopicMessageStoragePolicyOutput {
	return o.ApplyT(func (v *TopicMessageStoragePolicy) TopicMessageStoragePolicy { return *v }).(TopicMessageStoragePolicyOutput)
}

func (o TopicMessageStoragePolicyPtrOutput) AllowedPersistenceRegions() pulumi.StringArrayOutput {
	return o.ApplyT(func (v TopicMessageStoragePolicy) []string { return v.AllowedPersistenceRegions }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(TopicMessageStoragePolicyOutput{})
	pulumi.RegisterOutputType(TopicMessageStoragePolicyPtrOutput{})
}
