// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package InterconnectAttachmentPrivateInterconnectInfo

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type InterconnectAttachmentPrivateInterconnectInfo struct {
	Tag8021q *int `pulumi:"tag8021q"`
}

type InterconnectAttachmentPrivateInterconnectInfoInput interface {
	pulumi.Input

	ToInterconnectAttachmentPrivateInterconnectInfoOutput() InterconnectAttachmentPrivateInterconnectInfoOutput
	ToInterconnectAttachmentPrivateInterconnectInfoOutputWithContext(context.Context) InterconnectAttachmentPrivateInterconnectInfoOutput
}

type InterconnectAttachmentPrivateInterconnectInfoArgs struct {
	Tag8021q pulumi.IntPtrInput `pulumi:"tag8021q"`
}

func (InterconnectAttachmentPrivateInterconnectInfoArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*InterconnectAttachmentPrivateInterconnectInfo)(nil)).Elem()
}

func (i InterconnectAttachmentPrivateInterconnectInfoArgs) ToInterconnectAttachmentPrivateInterconnectInfoOutput() InterconnectAttachmentPrivateInterconnectInfoOutput {
	return i.ToInterconnectAttachmentPrivateInterconnectInfoOutputWithContext(context.Background())
}

func (i InterconnectAttachmentPrivateInterconnectInfoArgs) ToInterconnectAttachmentPrivateInterconnectInfoOutputWithContext(ctx context.Context) InterconnectAttachmentPrivateInterconnectInfoOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InterconnectAttachmentPrivateInterconnectInfoOutput)
}

func (i InterconnectAttachmentPrivateInterconnectInfoArgs) ToInterconnectAttachmentPrivateInterconnectInfoPtrOutput() InterconnectAttachmentPrivateInterconnectInfoPtrOutput {
	return i.ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(context.Background())
}

func (i InterconnectAttachmentPrivateInterconnectInfoArgs) ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(ctx context.Context) InterconnectAttachmentPrivateInterconnectInfoPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InterconnectAttachmentPrivateInterconnectInfoOutput).ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(ctx)
}

type InterconnectAttachmentPrivateInterconnectInfoPtrInput interface {
	pulumi.Input

	ToInterconnectAttachmentPrivateInterconnectInfoPtrOutput() InterconnectAttachmentPrivateInterconnectInfoPtrOutput
	ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(context.Context) InterconnectAttachmentPrivateInterconnectInfoPtrOutput
}

type interconnectAttachmentPrivateInterconnectInfoPtrType InterconnectAttachmentPrivateInterconnectInfoArgs

func InterconnectAttachmentPrivateInterconnectInfoPtr(v *InterconnectAttachmentPrivateInterconnectInfoArgs) InterconnectAttachmentPrivateInterconnectInfoPtrInput {	return (*interconnectAttachmentPrivateInterconnectInfoPtrType)(v)
}

func (*interconnectAttachmentPrivateInterconnectInfoPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**InterconnectAttachmentPrivateInterconnectInfo)(nil)).Elem()
}

func (i *interconnectAttachmentPrivateInterconnectInfoPtrType) ToInterconnectAttachmentPrivateInterconnectInfoPtrOutput() InterconnectAttachmentPrivateInterconnectInfoPtrOutput {
	return i.ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(context.Background())
}

func (i *interconnectAttachmentPrivateInterconnectInfoPtrType) ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(ctx context.Context) InterconnectAttachmentPrivateInterconnectInfoPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InterconnectAttachmentPrivateInterconnectInfoPtrOutput)
}

type InterconnectAttachmentPrivateInterconnectInfoOutput struct { *pulumi.OutputState }

func (InterconnectAttachmentPrivateInterconnectInfoOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InterconnectAttachmentPrivateInterconnectInfo)(nil)).Elem()
}

func (o InterconnectAttachmentPrivateInterconnectInfoOutput) ToInterconnectAttachmentPrivateInterconnectInfoOutput() InterconnectAttachmentPrivateInterconnectInfoOutput {
	return o
}

func (o InterconnectAttachmentPrivateInterconnectInfoOutput) ToInterconnectAttachmentPrivateInterconnectInfoOutputWithContext(ctx context.Context) InterconnectAttachmentPrivateInterconnectInfoOutput {
	return o
}

func (o InterconnectAttachmentPrivateInterconnectInfoOutput) ToInterconnectAttachmentPrivateInterconnectInfoPtrOutput() InterconnectAttachmentPrivateInterconnectInfoPtrOutput {
	return o.ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(context.Background())
}

func (o InterconnectAttachmentPrivateInterconnectInfoOutput) ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(ctx context.Context) InterconnectAttachmentPrivateInterconnectInfoPtrOutput {
	return o.ApplyT(func(v InterconnectAttachmentPrivateInterconnectInfo) *InterconnectAttachmentPrivateInterconnectInfo {
		return &v
	}).(InterconnectAttachmentPrivateInterconnectInfoPtrOutput)
}
func (o InterconnectAttachmentPrivateInterconnectInfoOutput) Tag8021q() pulumi.IntPtrOutput {
	return o.ApplyT(func (v InterconnectAttachmentPrivateInterconnectInfo) *int { return v.Tag8021q }).(pulumi.IntPtrOutput)
}

type InterconnectAttachmentPrivateInterconnectInfoPtrOutput struct { *pulumi.OutputState}

func (InterconnectAttachmentPrivateInterconnectInfoPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InterconnectAttachmentPrivateInterconnectInfo)(nil)).Elem()
}

func (o InterconnectAttachmentPrivateInterconnectInfoPtrOutput) ToInterconnectAttachmentPrivateInterconnectInfoPtrOutput() InterconnectAttachmentPrivateInterconnectInfoPtrOutput {
	return o
}

func (o InterconnectAttachmentPrivateInterconnectInfoPtrOutput) ToInterconnectAttachmentPrivateInterconnectInfoPtrOutputWithContext(ctx context.Context) InterconnectAttachmentPrivateInterconnectInfoPtrOutput {
	return o
}

func (o InterconnectAttachmentPrivateInterconnectInfoPtrOutput) Elem() InterconnectAttachmentPrivateInterconnectInfoOutput {
	return o.ApplyT(func (v *InterconnectAttachmentPrivateInterconnectInfo) InterconnectAttachmentPrivateInterconnectInfo { return *v }).(InterconnectAttachmentPrivateInterconnectInfoOutput)
}

func (o InterconnectAttachmentPrivateInterconnectInfoPtrOutput) Tag8021q() pulumi.IntPtrOutput {
	return o.ApplyT(func (v InterconnectAttachmentPrivateInterconnectInfo) *int { return v.Tag8021q }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(InterconnectAttachmentPrivateInterconnectInfoOutput{})
	pulumi.RegisterOutputType(InterconnectAttachmentPrivateInterconnectInfoPtrOutput{})
}
