// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package AutoscalarAutoscalingPolicyMetric

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type AutoscalarAutoscalingPolicyMetric struct {
	Filter *string `pulumi:"filter"`
	Name string `pulumi:"name"`
	SingleInstanceAssignment *float64 `pulumi:"singleInstanceAssignment"`
	Target *float64 `pulumi:"target"`
	Type *string `pulumi:"type"`
}

type AutoscalarAutoscalingPolicyMetricInput interface {
	pulumi.Input

	ToAutoscalarAutoscalingPolicyMetricOutput() AutoscalarAutoscalingPolicyMetricOutput
	ToAutoscalarAutoscalingPolicyMetricOutputWithContext(context.Context) AutoscalarAutoscalingPolicyMetricOutput
}

type AutoscalarAutoscalingPolicyMetricArgs struct {
	Filter pulumi.StringPtrInput `pulumi:"filter"`
	Name pulumi.StringInput `pulumi:"name"`
	SingleInstanceAssignment pulumi.Float64PtrInput `pulumi:"singleInstanceAssignment"`
	Target pulumi.Float64PtrInput `pulumi:"target"`
	Type pulumi.StringPtrInput `pulumi:"type"`
}

func (AutoscalarAutoscalingPolicyMetricArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AutoscalarAutoscalingPolicyMetric)(nil)).Elem()
}

func (i AutoscalarAutoscalingPolicyMetricArgs) ToAutoscalarAutoscalingPolicyMetricOutput() AutoscalarAutoscalingPolicyMetricOutput {
	return i.ToAutoscalarAutoscalingPolicyMetricOutputWithContext(context.Background())
}

func (i AutoscalarAutoscalingPolicyMetricArgs) ToAutoscalarAutoscalingPolicyMetricOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyMetricOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AutoscalarAutoscalingPolicyMetricOutput)
}

type AutoscalarAutoscalingPolicyMetricArrayInput interface {
	pulumi.Input

	ToAutoscalarAutoscalingPolicyMetricArrayOutput() AutoscalarAutoscalingPolicyMetricArrayOutput
	ToAutoscalarAutoscalingPolicyMetricArrayOutputWithContext(context.Context) AutoscalarAutoscalingPolicyMetricArrayOutput
}

type AutoscalarAutoscalingPolicyMetricArray []AutoscalarAutoscalingPolicyMetricInput

func (AutoscalarAutoscalingPolicyMetricArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AutoscalarAutoscalingPolicyMetric)(nil)).Elem()
}

func (i AutoscalarAutoscalingPolicyMetricArray) ToAutoscalarAutoscalingPolicyMetricArrayOutput() AutoscalarAutoscalingPolicyMetricArrayOutput {
	return i.ToAutoscalarAutoscalingPolicyMetricArrayOutputWithContext(context.Background())
}

func (i AutoscalarAutoscalingPolicyMetricArray) ToAutoscalarAutoscalingPolicyMetricArrayOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyMetricArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AutoscalarAutoscalingPolicyMetricArrayOutput)
}

type AutoscalarAutoscalingPolicyMetricOutput struct { *pulumi.OutputState }

func (AutoscalarAutoscalingPolicyMetricOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AutoscalarAutoscalingPolicyMetric)(nil)).Elem()
}

func (o AutoscalarAutoscalingPolicyMetricOutput) ToAutoscalarAutoscalingPolicyMetricOutput() AutoscalarAutoscalingPolicyMetricOutput {
	return o
}

func (o AutoscalarAutoscalingPolicyMetricOutput) ToAutoscalarAutoscalingPolicyMetricOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyMetricOutput {
	return o
}

func (o AutoscalarAutoscalingPolicyMetricOutput) Filter() pulumi.StringPtrOutput {
	return o.ApplyT(func (v AutoscalarAutoscalingPolicyMetric) *string { return v.Filter }).(pulumi.StringPtrOutput)
}

func (o AutoscalarAutoscalingPolicyMetricOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func (v AutoscalarAutoscalingPolicyMetric) string { return v.Name }).(pulumi.StringOutput)
}

func (o AutoscalarAutoscalingPolicyMetricOutput) SingleInstanceAssignment() pulumi.Float64PtrOutput {
	return o.ApplyT(func (v AutoscalarAutoscalingPolicyMetric) *float64 { return v.SingleInstanceAssignment }).(pulumi.Float64PtrOutput)
}

func (o AutoscalarAutoscalingPolicyMetricOutput) Target() pulumi.Float64PtrOutput {
	return o.ApplyT(func (v AutoscalarAutoscalingPolicyMetric) *float64 { return v.Target }).(pulumi.Float64PtrOutput)
}

func (o AutoscalarAutoscalingPolicyMetricOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func (v AutoscalarAutoscalingPolicyMetric) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type AutoscalarAutoscalingPolicyMetricArrayOutput struct { *pulumi.OutputState}

func (AutoscalarAutoscalingPolicyMetricArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AutoscalarAutoscalingPolicyMetric)(nil)).Elem()
}

func (o AutoscalarAutoscalingPolicyMetricArrayOutput) ToAutoscalarAutoscalingPolicyMetricArrayOutput() AutoscalarAutoscalingPolicyMetricArrayOutput {
	return o
}

func (o AutoscalarAutoscalingPolicyMetricArrayOutput) ToAutoscalarAutoscalingPolicyMetricArrayOutputWithContext(ctx context.Context) AutoscalarAutoscalingPolicyMetricArrayOutput {
	return o
}

func (o AutoscalarAutoscalingPolicyMetricArrayOutput) Index(i pulumi.IntInput) AutoscalarAutoscalingPolicyMetricOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) AutoscalarAutoscalingPolicyMetric {
		return vs[0].([]AutoscalarAutoscalingPolicyMetric)[vs[1].(int)]
	}).(AutoscalarAutoscalingPolicyMetricOutput)
}

func init() {
	pulumi.RegisterOutputType(AutoscalarAutoscalingPolicyMetricOutput{})
	pulumi.RegisterOutputType(AutoscalarAutoscalingPolicyMetricArrayOutput{})
}
