// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package ReservationSpecificReservationInstancePropertiesLocalSsd

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type ReservationSpecificReservationInstancePropertiesLocalSsd struct {
	DiskSizeGb int `pulumi:"diskSizeGb"`
	Interface *string `pulumi:"interface"`
}

type ReservationSpecificReservationInstancePropertiesLocalSsdInput interface {
	pulumi.Input

	ToReservationSpecificReservationInstancePropertiesLocalSsdOutput() ReservationSpecificReservationInstancePropertiesLocalSsdOutput
	ToReservationSpecificReservationInstancePropertiesLocalSsdOutputWithContext(context.Context) ReservationSpecificReservationInstancePropertiesLocalSsdOutput
}

type ReservationSpecificReservationInstancePropertiesLocalSsdArgs struct {
	DiskSizeGb pulumi.IntInput `pulumi:"diskSizeGb"`
	Interface pulumi.StringPtrInput `pulumi:"interface"`
}

func (ReservationSpecificReservationInstancePropertiesLocalSsdArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ReservationSpecificReservationInstancePropertiesLocalSsd)(nil)).Elem()
}

func (i ReservationSpecificReservationInstancePropertiesLocalSsdArgs) ToReservationSpecificReservationInstancePropertiesLocalSsdOutput() ReservationSpecificReservationInstancePropertiesLocalSsdOutput {
	return i.ToReservationSpecificReservationInstancePropertiesLocalSsdOutputWithContext(context.Background())
}

func (i ReservationSpecificReservationInstancePropertiesLocalSsdArgs) ToReservationSpecificReservationInstancePropertiesLocalSsdOutputWithContext(ctx context.Context) ReservationSpecificReservationInstancePropertiesLocalSsdOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReservationSpecificReservationInstancePropertiesLocalSsdOutput)
}

type ReservationSpecificReservationInstancePropertiesLocalSsdArrayInput interface {
	pulumi.Input

	ToReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput() ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput
	ToReservationSpecificReservationInstancePropertiesLocalSsdArrayOutputWithContext(context.Context) ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput
}

type ReservationSpecificReservationInstancePropertiesLocalSsdArray []ReservationSpecificReservationInstancePropertiesLocalSsdInput

func (ReservationSpecificReservationInstancePropertiesLocalSsdArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ReservationSpecificReservationInstancePropertiesLocalSsd)(nil)).Elem()
}

func (i ReservationSpecificReservationInstancePropertiesLocalSsdArray) ToReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput() ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput {
	return i.ToReservationSpecificReservationInstancePropertiesLocalSsdArrayOutputWithContext(context.Background())
}

func (i ReservationSpecificReservationInstancePropertiesLocalSsdArray) ToReservationSpecificReservationInstancePropertiesLocalSsdArrayOutputWithContext(ctx context.Context) ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput)
}

type ReservationSpecificReservationInstancePropertiesLocalSsdOutput struct { *pulumi.OutputState }

func (ReservationSpecificReservationInstancePropertiesLocalSsdOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ReservationSpecificReservationInstancePropertiesLocalSsd)(nil)).Elem()
}

func (o ReservationSpecificReservationInstancePropertiesLocalSsdOutput) ToReservationSpecificReservationInstancePropertiesLocalSsdOutput() ReservationSpecificReservationInstancePropertiesLocalSsdOutput {
	return o
}

func (o ReservationSpecificReservationInstancePropertiesLocalSsdOutput) ToReservationSpecificReservationInstancePropertiesLocalSsdOutputWithContext(ctx context.Context) ReservationSpecificReservationInstancePropertiesLocalSsdOutput {
	return o
}

func (o ReservationSpecificReservationInstancePropertiesLocalSsdOutput) DiskSizeGb() pulumi.IntOutput {
	return o.ApplyT(func (v ReservationSpecificReservationInstancePropertiesLocalSsd) int { return v.DiskSizeGb }).(pulumi.IntOutput)
}

func (o ReservationSpecificReservationInstancePropertiesLocalSsdOutput) Interface() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ReservationSpecificReservationInstancePropertiesLocalSsd) *string { return v.Interface }).(pulumi.StringPtrOutput)
}

type ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput struct { *pulumi.OutputState}

func (ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ReservationSpecificReservationInstancePropertiesLocalSsd)(nil)).Elem()
}

func (o ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput) ToReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput() ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput {
	return o
}

func (o ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput) ToReservationSpecificReservationInstancePropertiesLocalSsdArrayOutputWithContext(ctx context.Context) ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput {
	return o
}

func (o ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput) Index(i pulumi.IntInput) ReservationSpecificReservationInstancePropertiesLocalSsdOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) ReservationSpecificReservationInstancePropertiesLocalSsd {
		return vs[0].([]ReservationSpecificReservationInstancePropertiesLocalSsd)[vs[1].(int)]
	}).(ReservationSpecificReservationInstancePropertiesLocalSsdOutput)
}

func init() {
	pulumi.RegisterOutputType(ReservationSpecificReservationInstancePropertiesLocalSsdOutput{})
	pulumi.RegisterOutputType(ReservationSpecificReservationInstancePropertiesLocalSsdArrayOutput{})
}
