// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package JobHadoopConfigLoggingConfig

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type JobHadoopConfigLoggingConfig struct {
	DriverLogLevels map[string]string `pulumi:"driverLogLevels"`
}

type JobHadoopConfigLoggingConfigInput interface {
	pulumi.Input

	ToJobHadoopConfigLoggingConfigOutput() JobHadoopConfigLoggingConfigOutput
	ToJobHadoopConfigLoggingConfigOutputWithContext(context.Context) JobHadoopConfigLoggingConfigOutput
}

type JobHadoopConfigLoggingConfigArgs struct {
	DriverLogLevels pulumi.StringMapInput `pulumi:"driverLogLevels"`
}

func (JobHadoopConfigLoggingConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*JobHadoopConfigLoggingConfig)(nil)).Elem()
}

func (i JobHadoopConfigLoggingConfigArgs) ToJobHadoopConfigLoggingConfigOutput() JobHadoopConfigLoggingConfigOutput {
	return i.ToJobHadoopConfigLoggingConfigOutputWithContext(context.Background())
}

func (i JobHadoopConfigLoggingConfigArgs) ToJobHadoopConfigLoggingConfigOutputWithContext(ctx context.Context) JobHadoopConfigLoggingConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHadoopConfigLoggingConfigOutput)
}

func (i JobHadoopConfigLoggingConfigArgs) ToJobHadoopConfigLoggingConfigPtrOutput() JobHadoopConfigLoggingConfigPtrOutput {
	return i.ToJobHadoopConfigLoggingConfigPtrOutputWithContext(context.Background())
}

func (i JobHadoopConfigLoggingConfigArgs) ToJobHadoopConfigLoggingConfigPtrOutputWithContext(ctx context.Context) JobHadoopConfigLoggingConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHadoopConfigLoggingConfigOutput).ToJobHadoopConfigLoggingConfigPtrOutputWithContext(ctx)
}

type JobHadoopConfigLoggingConfigPtrInput interface {
	pulumi.Input

	ToJobHadoopConfigLoggingConfigPtrOutput() JobHadoopConfigLoggingConfigPtrOutput
	ToJobHadoopConfigLoggingConfigPtrOutputWithContext(context.Context) JobHadoopConfigLoggingConfigPtrOutput
}

type jobHadoopConfigLoggingConfigPtrType JobHadoopConfigLoggingConfigArgs

func JobHadoopConfigLoggingConfigPtr(v *JobHadoopConfigLoggingConfigArgs) JobHadoopConfigLoggingConfigPtrInput {	return (*jobHadoopConfigLoggingConfigPtrType)(v)
}

func (*jobHadoopConfigLoggingConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**JobHadoopConfigLoggingConfig)(nil)).Elem()
}

func (i *jobHadoopConfigLoggingConfigPtrType) ToJobHadoopConfigLoggingConfigPtrOutput() JobHadoopConfigLoggingConfigPtrOutput {
	return i.ToJobHadoopConfigLoggingConfigPtrOutputWithContext(context.Background())
}

func (i *jobHadoopConfigLoggingConfigPtrType) ToJobHadoopConfigLoggingConfigPtrOutputWithContext(ctx context.Context) JobHadoopConfigLoggingConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHadoopConfigLoggingConfigPtrOutput)
}

type JobHadoopConfigLoggingConfigOutput struct { *pulumi.OutputState }

func (JobHadoopConfigLoggingConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*JobHadoopConfigLoggingConfig)(nil)).Elem()
}

func (o JobHadoopConfigLoggingConfigOutput) ToJobHadoopConfigLoggingConfigOutput() JobHadoopConfigLoggingConfigOutput {
	return o
}

func (o JobHadoopConfigLoggingConfigOutput) ToJobHadoopConfigLoggingConfigOutputWithContext(ctx context.Context) JobHadoopConfigLoggingConfigOutput {
	return o
}

func (o JobHadoopConfigLoggingConfigOutput) ToJobHadoopConfigLoggingConfigPtrOutput() JobHadoopConfigLoggingConfigPtrOutput {
	return o.ToJobHadoopConfigLoggingConfigPtrOutputWithContext(context.Background())
}

func (o JobHadoopConfigLoggingConfigOutput) ToJobHadoopConfigLoggingConfigPtrOutputWithContext(ctx context.Context) JobHadoopConfigLoggingConfigPtrOutput {
	return o.ApplyT(func(v JobHadoopConfigLoggingConfig) *JobHadoopConfigLoggingConfig {
		return &v
	}).(JobHadoopConfigLoggingConfigPtrOutput)
}
func (o JobHadoopConfigLoggingConfigOutput) DriverLogLevels() pulumi.StringMapOutput {
	return o.ApplyT(func (v JobHadoopConfigLoggingConfig) map[string]string { return v.DriverLogLevels }).(pulumi.StringMapOutput)
}

type JobHadoopConfigLoggingConfigPtrOutput struct { *pulumi.OutputState}

func (JobHadoopConfigLoggingConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**JobHadoopConfigLoggingConfig)(nil)).Elem()
}

func (o JobHadoopConfigLoggingConfigPtrOutput) ToJobHadoopConfigLoggingConfigPtrOutput() JobHadoopConfigLoggingConfigPtrOutput {
	return o
}

func (o JobHadoopConfigLoggingConfigPtrOutput) ToJobHadoopConfigLoggingConfigPtrOutputWithContext(ctx context.Context) JobHadoopConfigLoggingConfigPtrOutput {
	return o
}

func (o JobHadoopConfigLoggingConfigPtrOutput) Elem() JobHadoopConfigLoggingConfigOutput {
	return o.ApplyT(func (v *JobHadoopConfigLoggingConfig) JobHadoopConfigLoggingConfig { return *v }).(JobHadoopConfigLoggingConfigOutput)
}

func (o JobHadoopConfigLoggingConfigPtrOutput) DriverLogLevels() pulumi.StringMapOutput {
	return o.ApplyT(func (v JobHadoopConfigLoggingConfig) map[string]string { return v.DriverLogLevels }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(JobHadoopConfigLoggingConfigOutput{})
	pulumi.RegisterOutputType(JobHadoopConfigLoggingConfigPtrOutput{})
}
