// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package ClusterNodeConfigShieldedInstanceConfig

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type ClusterNodeConfigShieldedInstanceConfig struct {
	EnableIntegrityMonitoring *bool `pulumi:"enableIntegrityMonitoring"`
	EnableSecureBoot *bool `pulumi:"enableSecureBoot"`
}

type ClusterNodeConfigShieldedInstanceConfigInput interface {
	pulumi.Input

	ToClusterNodeConfigShieldedInstanceConfigOutput() ClusterNodeConfigShieldedInstanceConfigOutput
	ToClusterNodeConfigShieldedInstanceConfigOutputWithContext(context.Context) ClusterNodeConfigShieldedInstanceConfigOutput
}

type ClusterNodeConfigShieldedInstanceConfigArgs struct {
	EnableIntegrityMonitoring pulumi.BoolPtrInput `pulumi:"enableIntegrityMonitoring"`
	EnableSecureBoot pulumi.BoolPtrInput `pulumi:"enableSecureBoot"`
}

func (ClusterNodeConfigShieldedInstanceConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterNodeConfigShieldedInstanceConfig)(nil)).Elem()
}

func (i ClusterNodeConfigShieldedInstanceConfigArgs) ToClusterNodeConfigShieldedInstanceConfigOutput() ClusterNodeConfigShieldedInstanceConfigOutput {
	return i.ToClusterNodeConfigShieldedInstanceConfigOutputWithContext(context.Background())
}

func (i ClusterNodeConfigShieldedInstanceConfigArgs) ToClusterNodeConfigShieldedInstanceConfigOutputWithContext(ctx context.Context) ClusterNodeConfigShieldedInstanceConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterNodeConfigShieldedInstanceConfigOutput)
}

func (i ClusterNodeConfigShieldedInstanceConfigArgs) ToClusterNodeConfigShieldedInstanceConfigPtrOutput() ClusterNodeConfigShieldedInstanceConfigPtrOutput {
	return i.ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(context.Background())
}

func (i ClusterNodeConfigShieldedInstanceConfigArgs) ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(ctx context.Context) ClusterNodeConfigShieldedInstanceConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterNodeConfigShieldedInstanceConfigOutput).ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(ctx)
}

type ClusterNodeConfigShieldedInstanceConfigPtrInput interface {
	pulumi.Input

	ToClusterNodeConfigShieldedInstanceConfigPtrOutput() ClusterNodeConfigShieldedInstanceConfigPtrOutput
	ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(context.Context) ClusterNodeConfigShieldedInstanceConfigPtrOutput
}

type clusterNodeConfigShieldedInstanceConfigPtrType ClusterNodeConfigShieldedInstanceConfigArgs

func ClusterNodeConfigShieldedInstanceConfigPtr(v *ClusterNodeConfigShieldedInstanceConfigArgs) ClusterNodeConfigShieldedInstanceConfigPtrInput {	return (*clusterNodeConfigShieldedInstanceConfigPtrType)(v)
}

func (*clusterNodeConfigShieldedInstanceConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterNodeConfigShieldedInstanceConfig)(nil)).Elem()
}

func (i *clusterNodeConfigShieldedInstanceConfigPtrType) ToClusterNodeConfigShieldedInstanceConfigPtrOutput() ClusterNodeConfigShieldedInstanceConfigPtrOutput {
	return i.ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(context.Background())
}

func (i *clusterNodeConfigShieldedInstanceConfigPtrType) ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(ctx context.Context) ClusterNodeConfigShieldedInstanceConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterNodeConfigShieldedInstanceConfigPtrOutput)
}

type ClusterNodeConfigShieldedInstanceConfigOutput struct { *pulumi.OutputState }

func (ClusterNodeConfigShieldedInstanceConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterNodeConfigShieldedInstanceConfig)(nil)).Elem()
}

func (o ClusterNodeConfigShieldedInstanceConfigOutput) ToClusterNodeConfigShieldedInstanceConfigOutput() ClusterNodeConfigShieldedInstanceConfigOutput {
	return o
}

func (o ClusterNodeConfigShieldedInstanceConfigOutput) ToClusterNodeConfigShieldedInstanceConfigOutputWithContext(ctx context.Context) ClusterNodeConfigShieldedInstanceConfigOutput {
	return o
}

func (o ClusterNodeConfigShieldedInstanceConfigOutput) ToClusterNodeConfigShieldedInstanceConfigPtrOutput() ClusterNodeConfigShieldedInstanceConfigPtrOutput {
	return o.ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(context.Background())
}

func (o ClusterNodeConfigShieldedInstanceConfigOutput) ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(ctx context.Context) ClusterNodeConfigShieldedInstanceConfigPtrOutput {
	return o.ApplyT(func(v ClusterNodeConfigShieldedInstanceConfig) *ClusterNodeConfigShieldedInstanceConfig {
		return &v
	}).(ClusterNodeConfigShieldedInstanceConfigPtrOutput)
}
func (o ClusterNodeConfigShieldedInstanceConfigOutput) EnableIntegrityMonitoring() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v ClusterNodeConfigShieldedInstanceConfig) *bool { return v.EnableIntegrityMonitoring }).(pulumi.BoolPtrOutput)
}

func (o ClusterNodeConfigShieldedInstanceConfigOutput) EnableSecureBoot() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v ClusterNodeConfigShieldedInstanceConfig) *bool { return v.EnableSecureBoot }).(pulumi.BoolPtrOutput)
}

type ClusterNodeConfigShieldedInstanceConfigPtrOutput struct { *pulumi.OutputState}

func (ClusterNodeConfigShieldedInstanceConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterNodeConfigShieldedInstanceConfig)(nil)).Elem()
}

func (o ClusterNodeConfigShieldedInstanceConfigPtrOutput) ToClusterNodeConfigShieldedInstanceConfigPtrOutput() ClusterNodeConfigShieldedInstanceConfigPtrOutput {
	return o
}

func (o ClusterNodeConfigShieldedInstanceConfigPtrOutput) ToClusterNodeConfigShieldedInstanceConfigPtrOutputWithContext(ctx context.Context) ClusterNodeConfigShieldedInstanceConfigPtrOutput {
	return o
}

func (o ClusterNodeConfigShieldedInstanceConfigPtrOutput) Elem() ClusterNodeConfigShieldedInstanceConfigOutput {
	return o.ApplyT(func (v *ClusterNodeConfigShieldedInstanceConfig) ClusterNodeConfigShieldedInstanceConfig { return *v }).(ClusterNodeConfigShieldedInstanceConfigOutput)
}

func (o ClusterNodeConfigShieldedInstanceConfigPtrOutput) EnableIntegrityMonitoring() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v ClusterNodeConfigShieldedInstanceConfig) *bool { return v.EnableIntegrityMonitoring }).(pulumi.BoolPtrOutput)
}

func (o ClusterNodeConfigShieldedInstanceConfigPtrOutput) EnableSecureBoot() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v ClusterNodeConfigShieldedInstanceConfig) *bool { return v.EnableSecureBoot }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ClusterNodeConfigShieldedInstanceConfigOutput{})
	pulumi.RegisterOutputType(ClusterNodeConfigShieldedInstanceConfigPtrOutput{})
}
