// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package ServiceMetadata

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type ServiceMetadata struct {
	Annotations map[string]string `pulumi:"annotations"`
	Generation *int `pulumi:"generation"`
	Labels map[string]string `pulumi:"labels"`
	Namespace *string `pulumi:"namespace"`
	ResourceVersion *string `pulumi:"resourceVersion"`
	SelfLink *string `pulumi:"selfLink"`
	Uid *string `pulumi:"uid"`
}

type ServiceMetadataInput interface {
	pulumi.Input

	ToServiceMetadataOutput() ServiceMetadataOutput
	ToServiceMetadataOutputWithContext(context.Context) ServiceMetadataOutput
}

type ServiceMetadataArgs struct {
	Annotations pulumi.StringMapInput `pulumi:"annotations"`
	Generation pulumi.IntPtrInput `pulumi:"generation"`
	Labels pulumi.StringMapInput `pulumi:"labels"`
	Namespace pulumi.StringPtrInput `pulumi:"namespace"`
	ResourceVersion pulumi.StringPtrInput `pulumi:"resourceVersion"`
	SelfLink pulumi.StringPtrInput `pulumi:"selfLink"`
	Uid pulumi.StringPtrInput `pulumi:"uid"`
}

func (ServiceMetadataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceMetadata)(nil)).Elem()
}

func (i ServiceMetadataArgs) ToServiceMetadataOutput() ServiceMetadataOutput {
	return i.ToServiceMetadataOutputWithContext(context.Background())
}

func (i ServiceMetadataArgs) ToServiceMetadataOutputWithContext(ctx context.Context) ServiceMetadataOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceMetadataOutput)
}

func (i ServiceMetadataArgs) ToServiceMetadataPtrOutput() ServiceMetadataPtrOutput {
	return i.ToServiceMetadataPtrOutputWithContext(context.Background())
}

func (i ServiceMetadataArgs) ToServiceMetadataPtrOutputWithContext(ctx context.Context) ServiceMetadataPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceMetadataOutput).ToServiceMetadataPtrOutputWithContext(ctx)
}

type ServiceMetadataPtrInput interface {
	pulumi.Input

	ToServiceMetadataPtrOutput() ServiceMetadataPtrOutput
	ToServiceMetadataPtrOutputWithContext(context.Context) ServiceMetadataPtrOutput
}

type serviceMetadataPtrType ServiceMetadataArgs

func ServiceMetadataPtr(v *ServiceMetadataArgs) ServiceMetadataPtrInput {	return (*serviceMetadataPtrType)(v)
}

func (*serviceMetadataPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceMetadata)(nil)).Elem()
}

func (i *serviceMetadataPtrType) ToServiceMetadataPtrOutput() ServiceMetadataPtrOutput {
	return i.ToServiceMetadataPtrOutputWithContext(context.Background())
}

func (i *serviceMetadataPtrType) ToServiceMetadataPtrOutputWithContext(ctx context.Context) ServiceMetadataPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceMetadataPtrOutput)
}

type ServiceMetadataOutput struct { *pulumi.OutputState }

func (ServiceMetadataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceMetadata)(nil)).Elem()
}

func (o ServiceMetadataOutput) ToServiceMetadataOutput() ServiceMetadataOutput {
	return o
}

func (o ServiceMetadataOutput) ToServiceMetadataOutputWithContext(ctx context.Context) ServiceMetadataOutput {
	return o
}

func (o ServiceMetadataOutput) ToServiceMetadataPtrOutput() ServiceMetadataPtrOutput {
	return o.ToServiceMetadataPtrOutputWithContext(context.Background())
}

func (o ServiceMetadataOutput) ToServiceMetadataPtrOutputWithContext(ctx context.Context) ServiceMetadataPtrOutput {
	return o.ApplyT(func(v ServiceMetadata) *ServiceMetadata {
		return &v
	}).(ServiceMetadataPtrOutput)
}
func (o ServiceMetadataOutput) Annotations() pulumi.StringMapOutput {
	return o.ApplyT(func (v ServiceMetadata) map[string]string { return v.Annotations }).(pulumi.StringMapOutput)
}

func (o ServiceMetadataOutput) Generation() pulumi.IntPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *int { return v.Generation }).(pulumi.IntPtrOutput)
}

func (o ServiceMetadataOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func (v ServiceMetadata) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o ServiceMetadataOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

func (o ServiceMetadataOutput) ResourceVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *string { return v.ResourceVersion }).(pulumi.StringPtrOutput)
}

func (o ServiceMetadataOutput) SelfLink() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *string { return v.SelfLink }).(pulumi.StringPtrOutput)
}

func (o ServiceMetadataOutput) Uid() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *string { return v.Uid }).(pulumi.StringPtrOutput)
}

type ServiceMetadataPtrOutput struct { *pulumi.OutputState}

func (ServiceMetadataPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceMetadata)(nil)).Elem()
}

func (o ServiceMetadataPtrOutput) ToServiceMetadataPtrOutput() ServiceMetadataPtrOutput {
	return o
}

func (o ServiceMetadataPtrOutput) ToServiceMetadataPtrOutputWithContext(ctx context.Context) ServiceMetadataPtrOutput {
	return o
}

func (o ServiceMetadataPtrOutput) Elem() ServiceMetadataOutput {
	return o.ApplyT(func (v *ServiceMetadata) ServiceMetadata { return *v }).(ServiceMetadataOutput)
}

func (o ServiceMetadataPtrOutput) Annotations() pulumi.StringMapOutput {
	return o.ApplyT(func (v ServiceMetadata) map[string]string { return v.Annotations }).(pulumi.StringMapOutput)
}

func (o ServiceMetadataPtrOutput) Generation() pulumi.IntPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *int { return v.Generation }).(pulumi.IntPtrOutput)
}

func (o ServiceMetadataPtrOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func (v ServiceMetadata) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o ServiceMetadataPtrOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

func (o ServiceMetadataPtrOutput) ResourceVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *string { return v.ResourceVersion }).(pulumi.StringPtrOutput)
}

func (o ServiceMetadataPtrOutput) SelfLink() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *string { return v.SelfLink }).(pulumi.StringPtrOutput)
}

func (o ServiceMetadataPtrOutput) Uid() pulumi.StringPtrOutput {
	return o.ApplyT(func (v ServiceMetadata) *string { return v.Uid }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ServiceMetadataOutput{})
	pulumi.RegisterOutputType(ServiceMetadataPtrOutput{})
}
