// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package ClusterClusterConfigAutoscalingConfig

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type ClusterClusterConfigAutoscalingConfig struct {
	PolicyUri string `pulumi:"policyUri"`
}

type ClusterClusterConfigAutoscalingConfigInput interface {
	pulumi.Input

	ToClusterClusterConfigAutoscalingConfigOutput() ClusterClusterConfigAutoscalingConfigOutput
	ToClusterClusterConfigAutoscalingConfigOutputWithContext(context.Context) ClusterClusterConfigAutoscalingConfigOutput
}

type ClusterClusterConfigAutoscalingConfigArgs struct {
	PolicyUri pulumi.StringInput `pulumi:"policyUri"`
}

func (ClusterClusterConfigAutoscalingConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterClusterConfigAutoscalingConfig)(nil)).Elem()
}

func (i ClusterClusterConfigAutoscalingConfigArgs) ToClusterClusterConfigAutoscalingConfigOutput() ClusterClusterConfigAutoscalingConfigOutput {
	return i.ToClusterClusterConfigAutoscalingConfigOutputWithContext(context.Background())
}

func (i ClusterClusterConfigAutoscalingConfigArgs) ToClusterClusterConfigAutoscalingConfigOutputWithContext(ctx context.Context) ClusterClusterConfigAutoscalingConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterClusterConfigAutoscalingConfigOutput)
}

func (i ClusterClusterConfigAutoscalingConfigArgs) ToClusterClusterConfigAutoscalingConfigPtrOutput() ClusterClusterConfigAutoscalingConfigPtrOutput {
	return i.ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(context.Background())
}

func (i ClusterClusterConfigAutoscalingConfigArgs) ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(ctx context.Context) ClusterClusterConfigAutoscalingConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterClusterConfigAutoscalingConfigOutput).ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(ctx)
}

type ClusterClusterConfigAutoscalingConfigPtrInput interface {
	pulumi.Input

	ToClusterClusterConfigAutoscalingConfigPtrOutput() ClusterClusterConfigAutoscalingConfigPtrOutput
	ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(context.Context) ClusterClusterConfigAutoscalingConfigPtrOutput
}

type clusterClusterConfigAutoscalingConfigPtrType ClusterClusterConfigAutoscalingConfigArgs

func ClusterClusterConfigAutoscalingConfigPtr(v *ClusterClusterConfigAutoscalingConfigArgs) ClusterClusterConfigAutoscalingConfigPtrInput {	return (*clusterClusterConfigAutoscalingConfigPtrType)(v)
}

func (*clusterClusterConfigAutoscalingConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterClusterConfigAutoscalingConfig)(nil)).Elem()
}

func (i *clusterClusterConfigAutoscalingConfigPtrType) ToClusterClusterConfigAutoscalingConfigPtrOutput() ClusterClusterConfigAutoscalingConfigPtrOutput {
	return i.ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(context.Background())
}

func (i *clusterClusterConfigAutoscalingConfigPtrType) ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(ctx context.Context) ClusterClusterConfigAutoscalingConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterClusterConfigAutoscalingConfigPtrOutput)
}

type ClusterClusterConfigAutoscalingConfigOutput struct { *pulumi.OutputState }

func (ClusterClusterConfigAutoscalingConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterClusterConfigAutoscalingConfig)(nil)).Elem()
}

func (o ClusterClusterConfigAutoscalingConfigOutput) ToClusterClusterConfigAutoscalingConfigOutput() ClusterClusterConfigAutoscalingConfigOutput {
	return o
}

func (o ClusterClusterConfigAutoscalingConfigOutput) ToClusterClusterConfigAutoscalingConfigOutputWithContext(ctx context.Context) ClusterClusterConfigAutoscalingConfigOutput {
	return o
}

func (o ClusterClusterConfigAutoscalingConfigOutput) ToClusterClusterConfigAutoscalingConfigPtrOutput() ClusterClusterConfigAutoscalingConfigPtrOutput {
	return o.ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(context.Background())
}

func (o ClusterClusterConfigAutoscalingConfigOutput) ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(ctx context.Context) ClusterClusterConfigAutoscalingConfigPtrOutput {
	return o.ApplyT(func(v ClusterClusterConfigAutoscalingConfig) *ClusterClusterConfigAutoscalingConfig {
		return &v
	}).(ClusterClusterConfigAutoscalingConfigPtrOutput)
}
func (o ClusterClusterConfigAutoscalingConfigOutput) PolicyUri() pulumi.StringOutput {
	return o.ApplyT(func (v ClusterClusterConfigAutoscalingConfig) string { return v.PolicyUri }).(pulumi.StringOutput)
}

type ClusterClusterConfigAutoscalingConfigPtrOutput struct { *pulumi.OutputState}

func (ClusterClusterConfigAutoscalingConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterClusterConfigAutoscalingConfig)(nil)).Elem()
}

func (o ClusterClusterConfigAutoscalingConfigPtrOutput) ToClusterClusterConfigAutoscalingConfigPtrOutput() ClusterClusterConfigAutoscalingConfigPtrOutput {
	return o
}

func (o ClusterClusterConfigAutoscalingConfigPtrOutput) ToClusterClusterConfigAutoscalingConfigPtrOutputWithContext(ctx context.Context) ClusterClusterConfigAutoscalingConfigPtrOutput {
	return o
}

func (o ClusterClusterConfigAutoscalingConfigPtrOutput) Elem() ClusterClusterConfigAutoscalingConfigOutput {
	return o.ApplyT(func (v *ClusterClusterConfigAutoscalingConfig) ClusterClusterConfigAutoscalingConfig { return *v }).(ClusterClusterConfigAutoscalingConfigOutput)
}

func (o ClusterClusterConfigAutoscalingConfigPtrOutput) PolicyUri() pulumi.StringOutput {
	return o.ApplyT(func (v ClusterClusterConfigAutoscalingConfig) string { return v.PolicyUri }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(ClusterClusterConfigAutoscalingConfigOutput{})
	pulumi.RegisterOutputType(ClusterClusterConfigAutoscalingConfigPtrOutput{})
}
