// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package TransferJobTransferSpecTransferOptions

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type TransferJobTransferSpecTransferOptions struct {
	DeleteObjectsFromSourceAfterTransfer *bool `pulumi:"deleteObjectsFromSourceAfterTransfer"`
	DeleteObjectsUniqueInSink *bool `pulumi:"deleteObjectsUniqueInSink"`
	OverwriteObjectsAlreadyExistingInSink *bool `pulumi:"overwriteObjectsAlreadyExistingInSink"`
}

type TransferJobTransferSpecTransferOptionsInput interface {
	pulumi.Input

	ToTransferJobTransferSpecTransferOptionsOutput() TransferJobTransferSpecTransferOptionsOutput
	ToTransferJobTransferSpecTransferOptionsOutputWithContext(context.Context) TransferJobTransferSpecTransferOptionsOutput
}

type TransferJobTransferSpecTransferOptionsArgs struct {
	DeleteObjectsFromSourceAfterTransfer pulumi.BoolPtrInput `pulumi:"deleteObjectsFromSourceAfterTransfer"`
	DeleteObjectsUniqueInSink pulumi.BoolPtrInput `pulumi:"deleteObjectsUniqueInSink"`
	OverwriteObjectsAlreadyExistingInSink pulumi.BoolPtrInput `pulumi:"overwriteObjectsAlreadyExistingInSink"`
}

func (TransferJobTransferSpecTransferOptionsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TransferJobTransferSpecTransferOptions)(nil)).Elem()
}

func (i TransferJobTransferSpecTransferOptionsArgs) ToTransferJobTransferSpecTransferOptionsOutput() TransferJobTransferSpecTransferOptionsOutput {
	return i.ToTransferJobTransferSpecTransferOptionsOutputWithContext(context.Background())
}

func (i TransferJobTransferSpecTransferOptionsArgs) ToTransferJobTransferSpecTransferOptionsOutputWithContext(ctx context.Context) TransferJobTransferSpecTransferOptionsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TransferJobTransferSpecTransferOptionsOutput)
}

func (i TransferJobTransferSpecTransferOptionsArgs) ToTransferJobTransferSpecTransferOptionsPtrOutput() TransferJobTransferSpecTransferOptionsPtrOutput {
	return i.ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(context.Background())
}

func (i TransferJobTransferSpecTransferOptionsArgs) ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(ctx context.Context) TransferJobTransferSpecTransferOptionsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TransferJobTransferSpecTransferOptionsOutput).ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(ctx)
}

type TransferJobTransferSpecTransferOptionsPtrInput interface {
	pulumi.Input

	ToTransferJobTransferSpecTransferOptionsPtrOutput() TransferJobTransferSpecTransferOptionsPtrOutput
	ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(context.Context) TransferJobTransferSpecTransferOptionsPtrOutput
}

type transferJobTransferSpecTransferOptionsPtrType TransferJobTransferSpecTransferOptionsArgs

func TransferJobTransferSpecTransferOptionsPtr(v *TransferJobTransferSpecTransferOptionsArgs) TransferJobTransferSpecTransferOptionsPtrInput {	return (*transferJobTransferSpecTransferOptionsPtrType)(v)
}

func (*transferJobTransferSpecTransferOptionsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**TransferJobTransferSpecTransferOptions)(nil)).Elem()
}

func (i *transferJobTransferSpecTransferOptionsPtrType) ToTransferJobTransferSpecTransferOptionsPtrOutput() TransferJobTransferSpecTransferOptionsPtrOutput {
	return i.ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(context.Background())
}

func (i *transferJobTransferSpecTransferOptionsPtrType) ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(ctx context.Context) TransferJobTransferSpecTransferOptionsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TransferJobTransferSpecTransferOptionsPtrOutput)
}

type TransferJobTransferSpecTransferOptionsOutput struct { *pulumi.OutputState }

func (TransferJobTransferSpecTransferOptionsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TransferJobTransferSpecTransferOptions)(nil)).Elem()
}

func (o TransferJobTransferSpecTransferOptionsOutput) ToTransferJobTransferSpecTransferOptionsOutput() TransferJobTransferSpecTransferOptionsOutput {
	return o
}

func (o TransferJobTransferSpecTransferOptionsOutput) ToTransferJobTransferSpecTransferOptionsOutputWithContext(ctx context.Context) TransferJobTransferSpecTransferOptionsOutput {
	return o
}

func (o TransferJobTransferSpecTransferOptionsOutput) ToTransferJobTransferSpecTransferOptionsPtrOutput() TransferJobTransferSpecTransferOptionsPtrOutput {
	return o.ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(context.Background())
}

func (o TransferJobTransferSpecTransferOptionsOutput) ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(ctx context.Context) TransferJobTransferSpecTransferOptionsPtrOutput {
	return o.ApplyT(func(v TransferJobTransferSpecTransferOptions) *TransferJobTransferSpecTransferOptions {
		return &v
	}).(TransferJobTransferSpecTransferOptionsPtrOutput)
}
func (o TransferJobTransferSpecTransferOptionsOutput) DeleteObjectsFromSourceAfterTransfer() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v TransferJobTransferSpecTransferOptions) *bool { return v.DeleteObjectsFromSourceAfterTransfer }).(pulumi.BoolPtrOutput)
}

func (o TransferJobTransferSpecTransferOptionsOutput) DeleteObjectsUniqueInSink() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v TransferJobTransferSpecTransferOptions) *bool { return v.DeleteObjectsUniqueInSink }).(pulumi.BoolPtrOutput)
}

func (o TransferJobTransferSpecTransferOptionsOutput) OverwriteObjectsAlreadyExistingInSink() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v TransferJobTransferSpecTransferOptions) *bool { return v.OverwriteObjectsAlreadyExistingInSink }).(pulumi.BoolPtrOutput)
}

type TransferJobTransferSpecTransferOptionsPtrOutput struct { *pulumi.OutputState}

func (TransferJobTransferSpecTransferOptionsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TransferJobTransferSpecTransferOptions)(nil)).Elem()
}

func (o TransferJobTransferSpecTransferOptionsPtrOutput) ToTransferJobTransferSpecTransferOptionsPtrOutput() TransferJobTransferSpecTransferOptionsPtrOutput {
	return o
}

func (o TransferJobTransferSpecTransferOptionsPtrOutput) ToTransferJobTransferSpecTransferOptionsPtrOutputWithContext(ctx context.Context) TransferJobTransferSpecTransferOptionsPtrOutput {
	return o
}

func (o TransferJobTransferSpecTransferOptionsPtrOutput) Elem() TransferJobTransferSpecTransferOptionsOutput {
	return o.ApplyT(func (v *TransferJobTransferSpecTransferOptions) TransferJobTransferSpecTransferOptions { return *v }).(TransferJobTransferSpecTransferOptionsOutput)
}

func (o TransferJobTransferSpecTransferOptionsPtrOutput) DeleteObjectsFromSourceAfterTransfer() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v TransferJobTransferSpecTransferOptions) *bool { return v.DeleteObjectsFromSourceAfterTransfer }).(pulumi.BoolPtrOutput)
}

func (o TransferJobTransferSpecTransferOptionsPtrOutput) DeleteObjectsUniqueInSink() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v TransferJobTransferSpecTransferOptions) *bool { return v.DeleteObjectsUniqueInSink }).(pulumi.BoolPtrOutput)
}

func (o TransferJobTransferSpecTransferOptionsPtrOutput) OverwriteObjectsAlreadyExistingInSink() pulumi.BoolPtrOutput {
	return o.ApplyT(func (v TransferJobTransferSpecTransferOptions) *bool { return v.OverwriteObjectsAlreadyExistingInSink }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(TransferJobTransferSpecTransferOptionsOutput{})
	pulumi.RegisterOutputType(TransferJobTransferSpecTransferOptionsPtrOutput{})
}
