// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gcp.Compute.Outputs
{

    [OutputType]
    public sealed class InstanceGroupManagerVersion
    {
        /// <summary>
        /// - The full URL to an instance template from which all new instances of this version will be created.
        /// </summary>
        public readonly string InstanceTemplate;
        /// <summary>
        /// The name of the instance group manager. Must be 1-63
        /// characters long and comply with
        /// [RFC1035](https://www.ietf.org/rfc/rfc1035.txt). Supported characters
        /// include lowercase letters, numbers, and hyphens.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The target number of running instances for this managed
        /// instance group. This value should always be explicitly set unless this resource is attached to
        /// an autoscaler, in which case it should never be set. Defaults to `0`.
        /// </summary>
        public readonly Outputs.InstanceGroupManagerVersionTargetSize? TargetSize;

        [OutputConstructor]
        private InstanceGroupManagerVersion(
            string instanceTemplate,

            string? name,

            Outputs.InstanceGroupManagerVersionTargetSize? targetSize)
        {
            InstanceTemplate = instanceTemplate;
            Name = name;
            TargetSize = targetSize;
        }
    }
}
