// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package SubscriptionPushConfig

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"https:/github.com/pulumi/pulumi-gcp/pubsub/SubscriptionPushConfigOidcToken"
)

type SubscriptionPushConfig struct {
	Attributes map[string]string `pulumi:"attributes"`
	OidcToken *pubsubSubscriptionPushConfigOidcToken.SubscriptionPushConfigOidcToken `pulumi:"oidcToken"`
	PushEndpoint string `pulumi:"pushEndpoint"`
}

type SubscriptionPushConfigInput interface {
	pulumi.Input

	ToSubscriptionPushConfigOutput() SubscriptionPushConfigOutput
	ToSubscriptionPushConfigOutputWithContext(context.Context) SubscriptionPushConfigOutput
}

type SubscriptionPushConfigArgs struct {
	Attributes pulumi.StringMapInput `pulumi:"attributes"`
	OidcToken pubsubSubscriptionPushConfigOidcToken.SubscriptionPushConfigOidcTokenPtrInput `pulumi:"oidcToken"`
	PushEndpoint pulumi.StringInput `pulumi:"pushEndpoint"`
}

func (SubscriptionPushConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SubscriptionPushConfig)(nil)).Elem()
}

func (i SubscriptionPushConfigArgs) ToSubscriptionPushConfigOutput() SubscriptionPushConfigOutput {
	return i.ToSubscriptionPushConfigOutputWithContext(context.Background())
}

func (i SubscriptionPushConfigArgs) ToSubscriptionPushConfigOutputWithContext(ctx context.Context) SubscriptionPushConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubscriptionPushConfigOutput)
}

func (i SubscriptionPushConfigArgs) ToSubscriptionPushConfigPtrOutput() SubscriptionPushConfigPtrOutput {
	return i.ToSubscriptionPushConfigPtrOutputWithContext(context.Background())
}

func (i SubscriptionPushConfigArgs) ToSubscriptionPushConfigPtrOutputWithContext(ctx context.Context) SubscriptionPushConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubscriptionPushConfigOutput).ToSubscriptionPushConfigPtrOutputWithContext(ctx)
}

type SubscriptionPushConfigPtrInput interface {
	pulumi.Input

	ToSubscriptionPushConfigPtrOutput() SubscriptionPushConfigPtrOutput
	ToSubscriptionPushConfigPtrOutputWithContext(context.Context) SubscriptionPushConfigPtrOutput
}

type subscriptionPushConfigPtrType SubscriptionPushConfigArgs

func SubscriptionPushConfigPtr(v *SubscriptionPushConfigArgs) SubscriptionPushConfigPtrInput {	return (*subscriptionPushConfigPtrType)(v)
}

func (*subscriptionPushConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SubscriptionPushConfig)(nil)).Elem()
}

func (i *subscriptionPushConfigPtrType) ToSubscriptionPushConfigPtrOutput() SubscriptionPushConfigPtrOutput {
	return i.ToSubscriptionPushConfigPtrOutputWithContext(context.Background())
}

func (i *subscriptionPushConfigPtrType) ToSubscriptionPushConfigPtrOutputWithContext(ctx context.Context) SubscriptionPushConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubscriptionPushConfigPtrOutput)
}

type SubscriptionPushConfigOutput struct { *pulumi.OutputState }

func (SubscriptionPushConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SubscriptionPushConfig)(nil)).Elem()
}

func (o SubscriptionPushConfigOutput) ToSubscriptionPushConfigOutput() SubscriptionPushConfigOutput {
	return o
}

func (o SubscriptionPushConfigOutput) ToSubscriptionPushConfigOutputWithContext(ctx context.Context) SubscriptionPushConfigOutput {
	return o
}

func (o SubscriptionPushConfigOutput) ToSubscriptionPushConfigPtrOutput() SubscriptionPushConfigPtrOutput {
	return o.ToSubscriptionPushConfigPtrOutputWithContext(context.Background())
}

func (o SubscriptionPushConfigOutput) ToSubscriptionPushConfigPtrOutputWithContext(ctx context.Context) SubscriptionPushConfigPtrOutput {
	return o.ApplyT(func(v SubscriptionPushConfig) *SubscriptionPushConfig {
		return &v
	}).(SubscriptionPushConfigPtrOutput)
}
func (o SubscriptionPushConfigOutput) Attributes() pulumi.StringMapOutput {
	return o.ApplyT(func (v SubscriptionPushConfig) map[string]string { return v.Attributes }).(pulumi.StringMapOutput)
}

func (o SubscriptionPushConfigOutput) OidcToken() pubsubSubscriptionPushConfigOidcToken.SubscriptionPushConfigOidcTokenPtrOutput {
	return o.ApplyT(func (v SubscriptionPushConfig) *pubsubSubscriptionPushConfigOidcToken.SubscriptionPushConfigOidcToken { return v.OidcToken }).(pubsubSubscriptionPushConfigOidcToken.SubscriptionPushConfigOidcTokenPtrOutput)
}

func (o SubscriptionPushConfigOutput) PushEndpoint() pulumi.StringOutput {
	return o.ApplyT(func (v SubscriptionPushConfig) string { return v.PushEndpoint }).(pulumi.StringOutput)
}

type SubscriptionPushConfigPtrOutput struct { *pulumi.OutputState}

func (SubscriptionPushConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SubscriptionPushConfig)(nil)).Elem()
}

func (o SubscriptionPushConfigPtrOutput) ToSubscriptionPushConfigPtrOutput() SubscriptionPushConfigPtrOutput {
	return o
}

func (o SubscriptionPushConfigPtrOutput) ToSubscriptionPushConfigPtrOutputWithContext(ctx context.Context) SubscriptionPushConfigPtrOutput {
	return o
}

func (o SubscriptionPushConfigPtrOutput) Elem() SubscriptionPushConfigOutput {
	return o.ApplyT(func (v *SubscriptionPushConfig) SubscriptionPushConfig { return *v }).(SubscriptionPushConfigOutput)
}

func (o SubscriptionPushConfigPtrOutput) Attributes() pulumi.StringMapOutput {
	return o.ApplyT(func (v SubscriptionPushConfig) map[string]string { return v.Attributes }).(pulumi.StringMapOutput)
}

func (o SubscriptionPushConfigPtrOutput) OidcToken() pubsubSubscriptionPushConfigOidcToken.SubscriptionPushConfigOidcTokenPtrOutput {
	return o.ApplyT(func (v SubscriptionPushConfig) *pubsubSubscriptionPushConfigOidcToken.SubscriptionPushConfigOidcToken { return v.OidcToken }).(pubsubSubscriptionPushConfigOidcToken.SubscriptionPushConfigOidcTokenPtrOutput)
}

func (o SubscriptionPushConfigPtrOutput) PushEndpoint() pulumi.StringOutput {
	return o.ApplyT(func (v SubscriptionPushConfig) string { return v.PushEndpoint }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(SubscriptionPushConfigOutput{})
	pulumi.RegisterOutputType(SubscriptionPushConfigPtrOutput{})
}
