// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package HealthCheckSslHealthCheck

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type HealthCheckSslHealthCheck struct {
	Port *int `pulumi:"port"`
	PortName *string `pulumi:"portName"`
	PortSpecification *string `pulumi:"portSpecification"`
	ProxyHeader *string `pulumi:"proxyHeader"`
	Request *string `pulumi:"request"`
	Response *string `pulumi:"response"`
}

type HealthCheckSslHealthCheckInput interface {
	pulumi.Input

	ToHealthCheckSslHealthCheckOutput() HealthCheckSslHealthCheckOutput
	ToHealthCheckSslHealthCheckOutputWithContext(context.Context) HealthCheckSslHealthCheckOutput
}

type HealthCheckSslHealthCheckArgs struct {
	Port pulumi.IntPtrInput `pulumi:"port"`
	PortName pulumi.StringPtrInput `pulumi:"portName"`
	PortSpecification pulumi.StringPtrInput `pulumi:"portSpecification"`
	ProxyHeader pulumi.StringPtrInput `pulumi:"proxyHeader"`
	Request pulumi.StringPtrInput `pulumi:"request"`
	Response pulumi.StringPtrInput `pulumi:"response"`
}

func (HealthCheckSslHealthCheckArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*HealthCheckSslHealthCheck)(nil)).Elem()
}

func (i HealthCheckSslHealthCheckArgs) ToHealthCheckSslHealthCheckOutput() HealthCheckSslHealthCheckOutput {
	return i.ToHealthCheckSslHealthCheckOutputWithContext(context.Background())
}

func (i HealthCheckSslHealthCheckArgs) ToHealthCheckSslHealthCheckOutputWithContext(ctx context.Context) HealthCheckSslHealthCheckOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HealthCheckSslHealthCheckOutput)
}

func (i HealthCheckSslHealthCheckArgs) ToHealthCheckSslHealthCheckPtrOutput() HealthCheckSslHealthCheckPtrOutput {
	return i.ToHealthCheckSslHealthCheckPtrOutputWithContext(context.Background())
}

func (i HealthCheckSslHealthCheckArgs) ToHealthCheckSslHealthCheckPtrOutputWithContext(ctx context.Context) HealthCheckSslHealthCheckPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HealthCheckSslHealthCheckOutput).ToHealthCheckSslHealthCheckPtrOutputWithContext(ctx)
}

type HealthCheckSslHealthCheckPtrInput interface {
	pulumi.Input

	ToHealthCheckSslHealthCheckPtrOutput() HealthCheckSslHealthCheckPtrOutput
	ToHealthCheckSslHealthCheckPtrOutputWithContext(context.Context) HealthCheckSslHealthCheckPtrOutput
}

type healthCheckSslHealthCheckPtrType HealthCheckSslHealthCheckArgs

func HealthCheckSslHealthCheckPtr(v *HealthCheckSslHealthCheckArgs) HealthCheckSslHealthCheckPtrInput {	return (*healthCheckSslHealthCheckPtrType)(v)
}

func (*healthCheckSslHealthCheckPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**HealthCheckSslHealthCheck)(nil)).Elem()
}

func (i *healthCheckSslHealthCheckPtrType) ToHealthCheckSslHealthCheckPtrOutput() HealthCheckSslHealthCheckPtrOutput {
	return i.ToHealthCheckSslHealthCheckPtrOutputWithContext(context.Background())
}

func (i *healthCheckSslHealthCheckPtrType) ToHealthCheckSslHealthCheckPtrOutputWithContext(ctx context.Context) HealthCheckSslHealthCheckPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HealthCheckSslHealthCheckPtrOutput)
}

type HealthCheckSslHealthCheckOutput struct { *pulumi.OutputState }

func (HealthCheckSslHealthCheckOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*HealthCheckSslHealthCheck)(nil)).Elem()
}

func (o HealthCheckSslHealthCheckOutput) ToHealthCheckSslHealthCheckOutput() HealthCheckSslHealthCheckOutput {
	return o
}

func (o HealthCheckSslHealthCheckOutput) ToHealthCheckSslHealthCheckOutputWithContext(ctx context.Context) HealthCheckSslHealthCheckOutput {
	return o
}

func (o HealthCheckSslHealthCheckOutput) ToHealthCheckSslHealthCheckPtrOutput() HealthCheckSslHealthCheckPtrOutput {
	return o.ToHealthCheckSslHealthCheckPtrOutputWithContext(context.Background())
}

func (o HealthCheckSslHealthCheckOutput) ToHealthCheckSslHealthCheckPtrOutputWithContext(ctx context.Context) HealthCheckSslHealthCheckPtrOutput {
	return o.ApplyT(func(v HealthCheckSslHealthCheck) *HealthCheckSslHealthCheck {
		return &v
	}).(HealthCheckSslHealthCheckPtrOutput)
}
func (o HealthCheckSslHealthCheckOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *int { return v.Port }).(pulumi.IntPtrOutput)
}

func (o HealthCheckSslHealthCheckOutput) PortName() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.PortName }).(pulumi.StringPtrOutput)
}

func (o HealthCheckSslHealthCheckOutput) PortSpecification() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.PortSpecification }).(pulumi.StringPtrOutput)
}

func (o HealthCheckSslHealthCheckOutput) ProxyHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.ProxyHeader }).(pulumi.StringPtrOutput)
}

func (o HealthCheckSslHealthCheckOutput) Request() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.Request }).(pulumi.StringPtrOutput)
}

func (o HealthCheckSslHealthCheckOutput) Response() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.Response }).(pulumi.StringPtrOutput)
}

type HealthCheckSslHealthCheckPtrOutput struct { *pulumi.OutputState}

func (HealthCheckSslHealthCheckPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HealthCheckSslHealthCheck)(nil)).Elem()
}

func (o HealthCheckSslHealthCheckPtrOutput) ToHealthCheckSslHealthCheckPtrOutput() HealthCheckSslHealthCheckPtrOutput {
	return o
}

func (o HealthCheckSslHealthCheckPtrOutput) ToHealthCheckSslHealthCheckPtrOutputWithContext(ctx context.Context) HealthCheckSslHealthCheckPtrOutput {
	return o
}

func (o HealthCheckSslHealthCheckPtrOutput) Elem() HealthCheckSslHealthCheckOutput {
	return o.ApplyT(func (v *HealthCheckSslHealthCheck) HealthCheckSslHealthCheck { return *v }).(HealthCheckSslHealthCheckOutput)
}

func (o HealthCheckSslHealthCheckPtrOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *int { return v.Port }).(pulumi.IntPtrOutput)
}

func (o HealthCheckSslHealthCheckPtrOutput) PortName() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.PortName }).(pulumi.StringPtrOutput)
}

func (o HealthCheckSslHealthCheckPtrOutput) PortSpecification() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.PortSpecification }).(pulumi.StringPtrOutput)
}

func (o HealthCheckSslHealthCheckPtrOutput) ProxyHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.ProxyHeader }).(pulumi.StringPtrOutput)
}

func (o HealthCheckSslHealthCheckPtrOutput) Request() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.Request }).(pulumi.StringPtrOutput)
}

func (o HealthCheckSslHealthCheckPtrOutput) Response() pulumi.StringPtrOutput {
	return o.ApplyT(func (v HealthCheckSslHealthCheck) *string { return v.Response }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(HealthCheckSslHealthCheckOutput{})
	pulumi.RegisterOutputType(HealthCheckSslHealthCheckPtrOutput{})
}
