// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package RegionUrlMapTest

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type RegionUrlMapTest struct {
	Description *string `pulumi:"description"`
	Host string `pulumi:"host"`
	Path string `pulumi:"path"`
	Service string `pulumi:"service"`
}

type RegionUrlMapTestInput interface {
	pulumi.Input

	ToRegionUrlMapTestOutput() RegionUrlMapTestOutput
	ToRegionUrlMapTestOutputWithContext(context.Context) RegionUrlMapTestOutput
}

type RegionUrlMapTestArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Host pulumi.StringInput `pulumi:"host"`
	Path pulumi.StringInput `pulumi:"path"`
	Service pulumi.StringInput `pulumi:"service"`
}

func (RegionUrlMapTestArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RegionUrlMapTest)(nil)).Elem()
}

func (i RegionUrlMapTestArgs) ToRegionUrlMapTestOutput() RegionUrlMapTestOutput {
	return i.ToRegionUrlMapTestOutputWithContext(context.Background())
}

func (i RegionUrlMapTestArgs) ToRegionUrlMapTestOutputWithContext(ctx context.Context) RegionUrlMapTestOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegionUrlMapTestOutput)
}

type RegionUrlMapTestArrayInput interface {
	pulumi.Input

	ToRegionUrlMapTestArrayOutput() RegionUrlMapTestArrayOutput
	ToRegionUrlMapTestArrayOutputWithContext(context.Context) RegionUrlMapTestArrayOutput
}

type RegionUrlMapTestArray []RegionUrlMapTestInput

func (RegionUrlMapTestArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RegionUrlMapTest)(nil)).Elem()
}

func (i RegionUrlMapTestArray) ToRegionUrlMapTestArrayOutput() RegionUrlMapTestArrayOutput {
	return i.ToRegionUrlMapTestArrayOutputWithContext(context.Background())
}

func (i RegionUrlMapTestArray) ToRegionUrlMapTestArrayOutputWithContext(ctx context.Context) RegionUrlMapTestArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegionUrlMapTestArrayOutput)
}

type RegionUrlMapTestOutput struct { *pulumi.OutputState }

func (RegionUrlMapTestOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RegionUrlMapTest)(nil)).Elem()
}

func (o RegionUrlMapTestOutput) ToRegionUrlMapTestOutput() RegionUrlMapTestOutput {
	return o
}

func (o RegionUrlMapTestOutput) ToRegionUrlMapTestOutputWithContext(ctx context.Context) RegionUrlMapTestOutput {
	return o
}

func (o RegionUrlMapTestOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func (v RegionUrlMapTest) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o RegionUrlMapTestOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func (v RegionUrlMapTest) string { return v.Host }).(pulumi.StringOutput)
}

func (o RegionUrlMapTestOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func (v RegionUrlMapTest) string { return v.Path }).(pulumi.StringOutput)
}

func (o RegionUrlMapTestOutput) Service() pulumi.StringOutput {
	return o.ApplyT(func (v RegionUrlMapTest) string { return v.Service }).(pulumi.StringOutput)
}

type RegionUrlMapTestArrayOutput struct { *pulumi.OutputState}

func (RegionUrlMapTestArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RegionUrlMapTest)(nil)).Elem()
}

func (o RegionUrlMapTestArrayOutput) ToRegionUrlMapTestArrayOutput() RegionUrlMapTestArrayOutput {
	return o
}

func (o RegionUrlMapTestArrayOutput) ToRegionUrlMapTestArrayOutputWithContext(ctx context.Context) RegionUrlMapTestArrayOutput {
	return o
}

func (o RegionUrlMapTestArrayOutput) Index(i pulumi.IntInput) RegionUrlMapTestOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) RegionUrlMapTest {
		return vs[0].([]RegionUrlMapTest)[vs[1].(int)]
	}).(RegionUrlMapTestOutput)
}

func init() {
	pulumi.RegisterOutputType(RegionUrlMapTestOutput{})
	pulumi.RegisterOutputType(RegionUrlMapTestArrayOutput{})
}
