// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputApi from "../../../types/input";
import * as outputApi from "../../../types/output";
import * as utilities from "../../../utilities";

export interface EnvironmentConfig {
    airflowUri: string;
    dagGcsPrefix: string;
    gkeCluster: string;
    nodeConfig: outputApi.composer.EnvironmentConfigNodeConfig;
    nodeCount: number;
    privateEnvironmentConfig: outputApi.composer.EnvironmentConfigPrivateEnvironmentConfig;
    softwareConfig: outputApi.composer.EnvironmentConfigSoftwareConfig;
}

export interface EnvironmentConfigNodeConfig {
    diskSizeGb: number;
    ipAllocationPolicy: outputApi.composer.EnvironmentConfigNodeConfigIpAllocationPolicy;
    machineType: string;
    network: string;
    oauthScopes: string[];
    serviceAccount: string;
    subnetwork?: string;
    tags?: string[];
    zone: string;
}

export interface EnvironmentConfigNodeConfigIpAllocationPolicy {
    clusterIpv4CidrBlock?: string;
    clusterSecondaryRangeName?: string;
    servicesIpv4CidrBlock?: string;
    servicesSecondaryRangeName?: string;
    useIpAliases?: boolean;
}

export interface EnvironmentConfigPrivateEnvironmentConfig {
    enablePrivateEndpoint?: boolean;
    masterIpv4CidrBlock?: string;
}

export interface EnvironmentConfigSoftwareConfig {
    airflowConfigOverrides?: {[key: string]: string};
    envVariables?: {[key: string]: string};
    imageVersion: string;
    pypiPackages?: {[key: string]: string};
    pythonVersion: string;
}
