# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Optional, Tuple, Union
from .. import _utilities, _tables

__all__ = [
    'EnvironmentContainerImage',
    'EnvironmentVmImage',
    'InstanceAcceleratorConfig',
    'InstanceContainerImage',
    'InstanceVmImage',
]

@pulumi.output_type
class EnvironmentContainerImage(dict):
    repository: str = pulumi.output_property("repository")
    """
    The path to the container image repository.
    For example: gcr.io/{project_id}/{imageName}
    """
    tag: Optional[str] = pulumi.output_property("tag")
    """
    The tag of the container image. If not specified, this defaults to the latest tag.
    """

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class EnvironmentVmImage(dict):
    image_family: Optional[str] = pulumi.output_property("imageFamily")
    """
    Use this VM image family to find the image; the newest image in this family will be used.
    """
    image_name: Optional[str] = pulumi.output_property("imageName")
    """
    Use VM image name to find the image.
    """
    project: str = pulumi.output_property("project")
    """
    The name of the Google Cloud project that this VM image belongs to.
    Format: projects/{project_id}
    """

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class InstanceAcceleratorConfig(dict):
    core_count: float = pulumi.output_property("coreCount")
    """
    Count of cores of this accelerator.
    """
    type: str = pulumi.output_property("type")
    """
    Type of this accelerator.
    """

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class InstanceContainerImage(dict):
    repository: str = pulumi.output_property("repository")
    """
    The path to the container image repository.
    For example: gcr.io/{project_id}/{imageName}
    """
    tag: Optional[str] = pulumi.output_property("tag")
    """
    The tag of the container image. If not specified, this defaults to the latest tag.
    """

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class InstanceVmImage(dict):
    image_family: Optional[str] = pulumi.output_property("imageFamily")
    """
    Use this VM image family to find the image; the newest image in this family will be used.
    """
    image_name: Optional[str] = pulumi.output_property("imageName")
    """
    Use VM image name to find the image.
    """
    project: str = pulumi.output_property("project")
    """
    The name of the Google Cloud project that this VM image belongs to.
    Format: projects/{project_id}
    """

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


