// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputApi from "../../../types/input";
import * as outputApi from "../../../types/output";
import * as utilities from "../../../utilities";

export interface RouterNatLogConfig {
    enable: boolean;
    filter: string;
}

export interface RouterNatSubnetwork {
    /**
     * A unique name for Cloud NAT, required by GCE. Changing
     * this forces a new NAT to be created.
     */
    name: string;
    secondaryIpRangeNames?: string[];
    sourceIpRangesToNats: string[];
}
