// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package InstanceIAMMemberCondition

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type InstanceIAMMemberCondition struct {
	Description *string `pulumi:"description"`
	Expression string `pulumi:"expression"`
	Title string `pulumi:"title"`
}

type InstanceIAMMemberConditionInput interface {
	pulumi.Input

	ToInstanceIAMMemberConditionOutput() InstanceIAMMemberConditionOutput
	ToInstanceIAMMemberConditionOutputWithContext(context.Context) InstanceIAMMemberConditionOutput
}

type InstanceIAMMemberConditionArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Expression pulumi.StringInput `pulumi:"expression"`
	Title pulumi.StringInput `pulumi:"title"`
}

func (InstanceIAMMemberConditionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceIAMMemberCondition)(nil)).Elem()
}

func (i InstanceIAMMemberConditionArgs) ToInstanceIAMMemberConditionOutput() InstanceIAMMemberConditionOutput {
	return i.ToInstanceIAMMemberConditionOutputWithContext(context.Background())
}

func (i InstanceIAMMemberConditionArgs) ToInstanceIAMMemberConditionOutputWithContext(ctx context.Context) InstanceIAMMemberConditionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIAMMemberConditionOutput)
}

func (i InstanceIAMMemberConditionArgs) ToInstanceIAMMemberConditionPtrOutput() InstanceIAMMemberConditionPtrOutput {
	return i.ToInstanceIAMMemberConditionPtrOutputWithContext(context.Background())
}

func (i InstanceIAMMemberConditionArgs) ToInstanceIAMMemberConditionPtrOutputWithContext(ctx context.Context) InstanceIAMMemberConditionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIAMMemberConditionOutput).ToInstanceIAMMemberConditionPtrOutputWithContext(ctx)
}

type InstanceIAMMemberConditionPtrInput interface {
	pulumi.Input

	ToInstanceIAMMemberConditionPtrOutput() InstanceIAMMemberConditionPtrOutput
	ToInstanceIAMMemberConditionPtrOutputWithContext(context.Context) InstanceIAMMemberConditionPtrOutput
}

type instanceIAMMemberConditionPtrType InstanceIAMMemberConditionArgs

func InstanceIAMMemberConditionPtr(v *InstanceIAMMemberConditionArgs) InstanceIAMMemberConditionPtrInput {	return (*instanceIAMMemberConditionPtrType)(v)
}

func (*instanceIAMMemberConditionPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceIAMMemberCondition)(nil)).Elem()
}

func (i *instanceIAMMemberConditionPtrType) ToInstanceIAMMemberConditionPtrOutput() InstanceIAMMemberConditionPtrOutput {
	return i.ToInstanceIAMMemberConditionPtrOutputWithContext(context.Background())
}

func (i *instanceIAMMemberConditionPtrType) ToInstanceIAMMemberConditionPtrOutputWithContext(ctx context.Context) InstanceIAMMemberConditionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceIAMMemberConditionPtrOutput)
}

type InstanceIAMMemberConditionOutput struct { *pulumi.OutputState }

func (InstanceIAMMemberConditionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceIAMMemberCondition)(nil)).Elem()
}

func (o InstanceIAMMemberConditionOutput) ToInstanceIAMMemberConditionOutput() InstanceIAMMemberConditionOutput {
	return o
}

func (o InstanceIAMMemberConditionOutput) ToInstanceIAMMemberConditionOutputWithContext(ctx context.Context) InstanceIAMMemberConditionOutput {
	return o
}

func (o InstanceIAMMemberConditionOutput) ToInstanceIAMMemberConditionPtrOutput() InstanceIAMMemberConditionPtrOutput {
	return o.ToInstanceIAMMemberConditionPtrOutputWithContext(context.Background())
}

func (o InstanceIAMMemberConditionOutput) ToInstanceIAMMemberConditionPtrOutputWithContext(ctx context.Context) InstanceIAMMemberConditionPtrOutput {
	return o.ApplyT(func(v InstanceIAMMemberCondition) *InstanceIAMMemberCondition {
		return &v
	}).(InstanceIAMMemberConditionPtrOutput)
}
func (o InstanceIAMMemberConditionOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func (v InstanceIAMMemberCondition) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o InstanceIAMMemberConditionOutput) Expression() pulumi.StringOutput {
	return o.ApplyT(func (v InstanceIAMMemberCondition) string { return v.Expression }).(pulumi.StringOutput)
}

func (o InstanceIAMMemberConditionOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func (v InstanceIAMMemberCondition) string { return v.Title }).(pulumi.StringOutput)
}

type InstanceIAMMemberConditionPtrOutput struct { *pulumi.OutputState}

func (InstanceIAMMemberConditionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceIAMMemberCondition)(nil)).Elem()
}

func (o InstanceIAMMemberConditionPtrOutput) ToInstanceIAMMemberConditionPtrOutput() InstanceIAMMemberConditionPtrOutput {
	return o
}

func (o InstanceIAMMemberConditionPtrOutput) ToInstanceIAMMemberConditionPtrOutputWithContext(ctx context.Context) InstanceIAMMemberConditionPtrOutput {
	return o
}

func (o InstanceIAMMemberConditionPtrOutput) Elem() InstanceIAMMemberConditionOutput {
	return o.ApplyT(func (v *InstanceIAMMemberCondition) InstanceIAMMemberCondition { return *v }).(InstanceIAMMemberConditionOutput)
}

func (o InstanceIAMMemberConditionPtrOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func (v InstanceIAMMemberCondition) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o InstanceIAMMemberConditionPtrOutput) Expression() pulumi.StringOutput {
	return o.ApplyT(func (v InstanceIAMMemberCondition) string { return v.Expression }).(pulumi.StringOutput)
}

func (o InstanceIAMMemberConditionPtrOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func (v InstanceIAMMemberCondition) string { return v.Title }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(InstanceIAMMemberConditionOutput{})
	pulumi.RegisterOutputType(InstanceIAMMemberConditionPtrOutput{})
}
