// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package JobHadoopConfig

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"https:/github.com/pulumi/pulumi-gcp/dataproc/JobHadoopConfigLoggingConfig"
)

type JobHadoopConfig struct {
	ArchiveUris []string `pulumi:"archiveUris"`
	Args []string `pulumi:"args"`
	FileUris []string `pulumi:"fileUris"`
	JarFileUris []string `pulumi:"jarFileUris"`
	LoggingConfig *dataprocJobHadoopConfigLoggingConfig.JobHadoopConfigLoggingConfig `pulumi:"loggingConfig"`
	MainClass *string `pulumi:"mainClass"`
	MainJarFileUri *string `pulumi:"mainJarFileUri"`
	Properties map[string]string `pulumi:"properties"`
}

type JobHadoopConfigInput interface {
	pulumi.Input

	ToJobHadoopConfigOutput() JobHadoopConfigOutput
	ToJobHadoopConfigOutputWithContext(context.Context) JobHadoopConfigOutput
}

type JobHadoopConfigArgs struct {
	ArchiveUris pulumi.StringArrayInput `pulumi:"archiveUris"`
	Args pulumi.StringArrayInput `pulumi:"args"`
	FileUris pulumi.StringArrayInput `pulumi:"fileUris"`
	JarFileUris pulumi.StringArrayInput `pulumi:"jarFileUris"`
	LoggingConfig dataprocJobHadoopConfigLoggingConfig.JobHadoopConfigLoggingConfigPtrInput `pulumi:"loggingConfig"`
	MainClass pulumi.StringPtrInput `pulumi:"mainClass"`
	MainJarFileUri pulumi.StringPtrInput `pulumi:"mainJarFileUri"`
	Properties pulumi.StringMapInput `pulumi:"properties"`
}

func (JobHadoopConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*JobHadoopConfig)(nil)).Elem()
}

func (i JobHadoopConfigArgs) ToJobHadoopConfigOutput() JobHadoopConfigOutput {
	return i.ToJobHadoopConfigOutputWithContext(context.Background())
}

func (i JobHadoopConfigArgs) ToJobHadoopConfigOutputWithContext(ctx context.Context) JobHadoopConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHadoopConfigOutput)
}

func (i JobHadoopConfigArgs) ToJobHadoopConfigPtrOutput() JobHadoopConfigPtrOutput {
	return i.ToJobHadoopConfigPtrOutputWithContext(context.Background())
}

func (i JobHadoopConfigArgs) ToJobHadoopConfigPtrOutputWithContext(ctx context.Context) JobHadoopConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHadoopConfigOutput).ToJobHadoopConfigPtrOutputWithContext(ctx)
}

type JobHadoopConfigPtrInput interface {
	pulumi.Input

	ToJobHadoopConfigPtrOutput() JobHadoopConfigPtrOutput
	ToJobHadoopConfigPtrOutputWithContext(context.Context) JobHadoopConfigPtrOutput
}

type jobHadoopConfigPtrType JobHadoopConfigArgs

func JobHadoopConfigPtr(v *JobHadoopConfigArgs) JobHadoopConfigPtrInput {	return (*jobHadoopConfigPtrType)(v)
}

func (*jobHadoopConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**JobHadoopConfig)(nil)).Elem()
}

func (i *jobHadoopConfigPtrType) ToJobHadoopConfigPtrOutput() JobHadoopConfigPtrOutput {
	return i.ToJobHadoopConfigPtrOutputWithContext(context.Background())
}

func (i *jobHadoopConfigPtrType) ToJobHadoopConfigPtrOutputWithContext(ctx context.Context) JobHadoopConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JobHadoopConfigPtrOutput)
}

type JobHadoopConfigOutput struct { *pulumi.OutputState }

func (JobHadoopConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*JobHadoopConfig)(nil)).Elem()
}

func (o JobHadoopConfigOutput) ToJobHadoopConfigOutput() JobHadoopConfigOutput {
	return o
}

func (o JobHadoopConfigOutput) ToJobHadoopConfigOutputWithContext(ctx context.Context) JobHadoopConfigOutput {
	return o
}

func (o JobHadoopConfigOutput) ToJobHadoopConfigPtrOutput() JobHadoopConfigPtrOutput {
	return o.ToJobHadoopConfigPtrOutputWithContext(context.Background())
}

func (o JobHadoopConfigOutput) ToJobHadoopConfigPtrOutputWithContext(ctx context.Context) JobHadoopConfigPtrOutput {
	return o.ApplyT(func(v JobHadoopConfig) *JobHadoopConfig {
		return &v
	}).(JobHadoopConfigPtrOutput)
}
func (o JobHadoopConfigOutput) ArchiveUris() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHadoopConfig) []string { return v.ArchiveUris }).(pulumi.StringArrayOutput)
}

func (o JobHadoopConfigOutput) Args() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHadoopConfig) []string { return v.Args }).(pulumi.StringArrayOutput)
}

func (o JobHadoopConfigOutput) FileUris() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHadoopConfig) []string { return v.FileUris }).(pulumi.StringArrayOutput)
}

func (o JobHadoopConfigOutput) JarFileUris() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHadoopConfig) []string { return v.JarFileUris }).(pulumi.StringArrayOutput)
}

func (o JobHadoopConfigOutput) LoggingConfig() dataprocJobHadoopConfigLoggingConfig.JobHadoopConfigLoggingConfigPtrOutput {
	return o.ApplyT(func (v JobHadoopConfig) *dataprocJobHadoopConfigLoggingConfig.JobHadoopConfigLoggingConfig { return v.LoggingConfig }).(dataprocJobHadoopConfigLoggingConfig.JobHadoopConfigLoggingConfigPtrOutput)
}

func (o JobHadoopConfigOutput) MainClass() pulumi.StringPtrOutput {
	return o.ApplyT(func (v JobHadoopConfig) *string { return v.MainClass }).(pulumi.StringPtrOutput)
}

func (o JobHadoopConfigOutput) MainJarFileUri() pulumi.StringPtrOutput {
	return o.ApplyT(func (v JobHadoopConfig) *string { return v.MainJarFileUri }).(pulumi.StringPtrOutput)
}

func (o JobHadoopConfigOutput) Properties() pulumi.StringMapOutput {
	return o.ApplyT(func (v JobHadoopConfig) map[string]string { return v.Properties }).(pulumi.StringMapOutput)
}

type JobHadoopConfigPtrOutput struct { *pulumi.OutputState}

func (JobHadoopConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**JobHadoopConfig)(nil)).Elem()
}

func (o JobHadoopConfigPtrOutput) ToJobHadoopConfigPtrOutput() JobHadoopConfigPtrOutput {
	return o
}

func (o JobHadoopConfigPtrOutput) ToJobHadoopConfigPtrOutputWithContext(ctx context.Context) JobHadoopConfigPtrOutput {
	return o
}

func (o JobHadoopConfigPtrOutput) Elem() JobHadoopConfigOutput {
	return o.ApplyT(func (v *JobHadoopConfig) JobHadoopConfig { return *v }).(JobHadoopConfigOutput)
}

func (o JobHadoopConfigPtrOutput) ArchiveUris() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHadoopConfig) []string { return v.ArchiveUris }).(pulumi.StringArrayOutput)
}

func (o JobHadoopConfigPtrOutput) Args() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHadoopConfig) []string { return v.Args }).(pulumi.StringArrayOutput)
}

func (o JobHadoopConfigPtrOutput) FileUris() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHadoopConfig) []string { return v.FileUris }).(pulumi.StringArrayOutput)
}

func (o JobHadoopConfigPtrOutput) JarFileUris() pulumi.StringArrayOutput {
	return o.ApplyT(func (v JobHadoopConfig) []string { return v.JarFileUris }).(pulumi.StringArrayOutput)
}

func (o JobHadoopConfigPtrOutput) LoggingConfig() dataprocJobHadoopConfigLoggingConfig.JobHadoopConfigLoggingConfigPtrOutput {
	return o.ApplyT(func (v JobHadoopConfig) *dataprocJobHadoopConfigLoggingConfig.JobHadoopConfigLoggingConfig { return v.LoggingConfig }).(dataprocJobHadoopConfigLoggingConfig.JobHadoopConfigLoggingConfigPtrOutput)
}

func (o JobHadoopConfigPtrOutput) MainClass() pulumi.StringPtrOutput {
	return o.ApplyT(func (v JobHadoopConfig) *string { return v.MainClass }).(pulumi.StringPtrOutput)
}

func (o JobHadoopConfigPtrOutput) MainJarFileUri() pulumi.StringPtrOutput {
	return o.ApplyT(func (v JobHadoopConfig) *string { return v.MainJarFileUri }).(pulumi.StringPtrOutput)
}

func (o JobHadoopConfigPtrOutput) Properties() pulumi.StringMapOutput {
	return o.ApplyT(func (v JobHadoopConfig) map[string]string { return v.Properties }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(JobHadoopConfigOutput{})
	pulumi.RegisterOutputType(JobHadoopConfigPtrOutput{})
}
