// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package getFunctionSourceRepository

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type GetFunctionSourceRepository struct {
	DeployedUrl string `pulumi:"deployedUrl"`
	Url string `pulumi:"url"`
}

type GetFunctionSourceRepositoryInput interface {
	pulumi.Input

	ToGetFunctionSourceRepositoryOutput() GetFunctionSourceRepositoryOutput
	ToGetFunctionSourceRepositoryOutputWithContext(context.Context) GetFunctionSourceRepositoryOutput
}

type GetFunctionSourceRepositoryArgs struct {
	DeployedUrl pulumi.StringInput `pulumi:"deployedUrl"`
	Url pulumi.StringInput `pulumi:"url"`
}

func (GetFunctionSourceRepositoryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFunctionSourceRepository)(nil)).Elem()
}

func (i GetFunctionSourceRepositoryArgs) ToGetFunctionSourceRepositoryOutput() GetFunctionSourceRepositoryOutput {
	return i.ToGetFunctionSourceRepositoryOutputWithContext(context.Background())
}

func (i GetFunctionSourceRepositoryArgs) ToGetFunctionSourceRepositoryOutputWithContext(ctx context.Context) GetFunctionSourceRepositoryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetFunctionSourceRepositoryOutput)
}

type GetFunctionSourceRepositoryArrayInput interface {
	pulumi.Input

	ToGetFunctionSourceRepositoryArrayOutput() GetFunctionSourceRepositoryArrayOutput
	ToGetFunctionSourceRepositoryArrayOutputWithContext(context.Context) GetFunctionSourceRepositoryArrayOutput
}

type GetFunctionSourceRepositoryArray []GetFunctionSourceRepositoryInput

func (GetFunctionSourceRepositoryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetFunctionSourceRepository)(nil)).Elem()
}

func (i GetFunctionSourceRepositoryArray) ToGetFunctionSourceRepositoryArrayOutput() GetFunctionSourceRepositoryArrayOutput {
	return i.ToGetFunctionSourceRepositoryArrayOutputWithContext(context.Background())
}

func (i GetFunctionSourceRepositoryArray) ToGetFunctionSourceRepositoryArrayOutputWithContext(ctx context.Context) GetFunctionSourceRepositoryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetFunctionSourceRepositoryArrayOutput)
}

type GetFunctionSourceRepositoryOutput struct { *pulumi.OutputState }

func (GetFunctionSourceRepositoryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFunctionSourceRepository)(nil)).Elem()
}

func (o GetFunctionSourceRepositoryOutput) ToGetFunctionSourceRepositoryOutput() GetFunctionSourceRepositoryOutput {
	return o
}

func (o GetFunctionSourceRepositoryOutput) ToGetFunctionSourceRepositoryOutputWithContext(ctx context.Context) GetFunctionSourceRepositoryOutput {
	return o
}

func (o GetFunctionSourceRepositoryOutput) DeployedUrl() pulumi.StringOutput {
	return o.ApplyT(func (v GetFunctionSourceRepository) string { return v.DeployedUrl }).(pulumi.StringOutput)
}

func (o GetFunctionSourceRepositoryOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func (v GetFunctionSourceRepository) string { return v.Url }).(pulumi.StringOutput)
}

type GetFunctionSourceRepositoryArrayOutput struct { *pulumi.OutputState}

func (GetFunctionSourceRepositoryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetFunctionSourceRepository)(nil)).Elem()
}

func (o GetFunctionSourceRepositoryArrayOutput) ToGetFunctionSourceRepositoryArrayOutput() GetFunctionSourceRepositoryArrayOutput {
	return o
}

func (o GetFunctionSourceRepositoryArrayOutput) ToGetFunctionSourceRepositoryArrayOutputWithContext(ctx context.Context) GetFunctionSourceRepositoryArrayOutput {
	return o
}

func (o GetFunctionSourceRepositoryArrayOutput) Index(i pulumi.IntInput) GetFunctionSourceRepositoryOutput {
	return pulumi.All(o, i).ApplyT(func (vs []interface{}) GetFunctionSourceRepository {
		return vs[0].([]GetFunctionSourceRepository)[vs[1].(int)]
	}).(GetFunctionSourceRepositoryOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFunctionSourceRepositoryOutput{})
	pulumi.RegisterOutputType(GetFunctionSourceRepositoryArrayOutput{})
}
