// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputApi from "../../../types/input";
import * as outputApi from "../../../types/output";
import * as utilities from "../../../utilities";

export interface AlertPolicyCondition {
    conditionAbsent?: outputApi.monitoring.AlertPolicyConditionConditionAbsent;
    conditionThreshold?: outputApi.monitoring.AlertPolicyConditionConditionThreshold;
    displayName: string;
    name: string;
}

export interface AlertPolicyConditionConditionAbsent {
    aggregations?: outputApi.monitoring.AlertPolicyConditionConditionAbsentAggregation[];
    duration: string;
    filter?: string;
    trigger?: outputApi.monitoring.AlertPolicyConditionConditionAbsentTrigger;
}

export interface AlertPolicyConditionConditionAbsentAggregation {
    alignmentPeriod?: string;
    crossSeriesReducer?: string;
    groupByFields?: string[];
    perSeriesAligner?: string;
}

export interface AlertPolicyConditionConditionAbsentTrigger {
    count?: number;
    percent?: number;
}

export interface AlertPolicyConditionConditionThreshold {
    aggregations?: outputApi.monitoring.AlertPolicyConditionConditionThresholdAggregation[];
    comparison: string;
    denominatorAggregations?: outputApi.monitoring.AlertPolicyConditionConditionThresholdDenominatorAggregation[];
    denominatorFilter?: string;
    duration: string;
    filter?: string;
    thresholdValue?: number;
    trigger?: outputApi.monitoring.AlertPolicyConditionConditionThresholdTrigger;
}

export interface AlertPolicyConditionConditionThresholdAggregation {
    alignmentPeriod?: string;
    crossSeriesReducer?: string;
    groupByFields?: string[];
    perSeriesAligner?: string;
}

export interface AlertPolicyConditionConditionThresholdDenominatorAggregation {
    alignmentPeriod?: string;
    crossSeriesReducer?: string;
    groupByFields?: string[];
    perSeriesAligner?: string;
}

export interface AlertPolicyConditionConditionThresholdTrigger {
    count?: number;
    percent?: number;
}

export interface AlertPolicyCreationRecord {
    mutateTime: string;
    mutatedBy: string;
}

export interface AlertPolicyDocumentation {
    content?: string;
    mimeType?: string;
}
